vuestorefront/shopware-pwa

- README.md
I've updated the documentation.
> docs(faker): add faker explaination

- packages/shopware-6-client/src/interfaces/response/Error.ts
It adds a common interface of response when the exception is thrown on API side.
> feat(error): add error response interface

- packages/default-theme/components/SwProductCard.vue
- packages/default-theme/components/cms/elements/CmsSwProductCart.vue
- packages/default-theme/components/cms/elements/SwProductListingSlot.vue
- packages/default-theme/components/cms/elements/SwProductSlider.vue
Closes #179 
Fixes:
- Added redirection to a specific product page after clicking on product block title or image.
- Fixed SwProductCard file name
> fix: product block (image, title) redirects to specific product page

- packages/default-theme/components/cms/elements/SwFooter.vue
- packages/default-theme/layouts/default.vue
Closes #188 #200 
Created sw-footer component and placed it at the bottom of every page
> feat(theme): Add footer for bottom part of our page

- packages/default-theme/components/SwProductCard.vue
- packages/default-theme/components/views/ProductView.vue
- packages/helpers/__tests__/product/getProductSpecialPrice.spec.ts
- packages/helpers/src/product/getProductSpecialPrice.ts
- packages/helpers/src/product/index.ts
- packages/shopware-6-client/src/interfaces/models/content/product/Product.ts
> Feat/helpers/special price #19

- packages/default-theme/components/TopNavigation.vue
Closes #232 
Added a badge to the navbar user button that indicates whether a user is logged in or not.
> feat(theme): Add a badge to the navbar button that indicates logged user

- .github/workflows/e2e-test.yml
will be fired on `e2e` label on PR if needed
> chore: temporary turn off unit tests

- packages/default-theme/components/SwProductCard.vue
- packages/default-theme/components/cms/elements/SwProductListingSlot.vue
Closes #281 
Added flex: 0 0 200px to temporary fix (waiting for SfUI fix) problem with diffrent image sizes in category page.
> fix(theme): restore same size for all images in category view

- packages/default-theme/components/TopNavigation.vue
related to #243, does not solve all the points.
> fix(theme): header logo

- packages/composables/src/hooks/useProductListing.ts
- packages/default-theme/components/SwProductCard.vue
- packages/default-theme/components/cms/elements/SwTextSlot.vue
- packages/helpers/__tests__/product/getProductName.spec.ts
- packages/helpers/__tests__/product/getVariantOptionsLabel.spec.ts
- packages/helpers/src/product/getProductName.ts
- packages/helpers/src/product/getVariantOptionsLabel.ts
- packages/helpers/src/product/index.ts
- packages/shopware-6-client/src/interfaces/models/content/product/Product.ts
closes #300 and #298 
to remember: handle same situation on page resolver when is ready
> feat: show proper product names, add product reviews

- packages/helpers/src/category/getCategoryAvailableFilters.ts
- packages/helpers/src/category/getCategoryAvailableSorting.ts
- packages/helpers/src/cms/getCmsSections.ts
- packages/helpers/src/listing/filters.ts
- packages/helpers/src/product/getProductMainImageUrl.ts
- packages/helpers/src/product/getProductMediaGallery.ts
- packages/helpers/src/product/getProductName.ts
- packages/helpers/src/product/getProductOption.ts
- packages/helpers/src/product/getProductOptions.ts
- packages/helpers/src/product/getProductOptionsUrl.ts
- packages/helpers/src/product/getProductProperties.ts
- packages/helpers/src/product/getProductRegularPrice.ts
- packages/helpers/src/product/getProductReviews.ts
- packages/helpers/src/product/getProductSpecialPrice.ts
- packages/helpers/src/product/getProductUrl.ts
- packages/helpers/src/product/getVariantOptionsLabel.ts
- packages/helpers/src/product/isProductSimple.ts
- packages/helpers/src/ui-interfaces.ts
- packages/helpers/src/urlHelpers.ts
covers #303 in terms of @shopware-pwa/helpers
> docs(helpers): add @alpha annotation to all the interfaces

- packages/composables/__tests__/useCms.spec.ts
- packages/composables/src/hooks/useCms/index.ts
- packages/default-theme/components/cms/elements/SwCategoryNavigationSlot.vue
- packages/default-theme/components/cms/elements/SwCategorySidebarFilter.vue
- packages/default-theme/layouts/default.vue
- makes breadcrumb clickable
- change side navigation logic
> feat(theme): improvements

- packages/default-theme/components/TopNavigation.vue
- packages/default-theme/package.json
- yarn.lock
> refactor(theme): fix logo sizing

- packages/composables/__tests__/useProduct.spec.ts
- packages/composables/src/hooks/useProduct/index.ts
- packages/default-theme/components/SwProductDetails.vue
- packages/default-theme/components/SwProductSelect.vue
- packages/default-theme/components/cms/elements/SwCategorySidebarFilter.vue
- packages/default-theme/components/views/ProductView.vue
- packages/helpers/__tests__/listing/filters.spec.ts
- packages/helpers/src/listing/filters.ts
- packages/shopware-6-client/src/apiService.ts
- scripts/linkDependencies.js
- autoselect current variant
- name and description is taken from translated object
additional:
- fix sorting select
- add sorting icons
> refactor(theme): variants on product page

- docs/.vuepress/config.js
- package.json
- scripts/generateDocs.js
- yarn.lock
**changes**
- created script that generate typedocs, finds all static files and copy them to /docs
- added plugin that create sidebar structure based on /docs folder structure
> feat(docs): add static files to docs

- package.json
- packages/helpers/__tests__/product/getProductMainImageUrl.spec.ts
- packages/helpers/__tests__/product/getProductOption.spec.ts
- packages/helpers/__tests__/product/getProductOptions.spec.ts
- packages/helpers/src/cms/getCmsSections.ts
- packages/helpers/src/product/getProductMainImageUrl.ts
- packages/helpers/src/product/getProductOption.ts
- packages/helpers/src/product/getProductOptions.ts
- packages/helpers/src/product/getProductProperties.ts
- packages/helpers/src/product/getProductRegularPrice.ts
- packages/helpers/src/product/getProductSpecialPrice.ts
- packages/helpers/src/product/isProductSimple.ts
- tsconfig.json
Refactored couple of elements to see if everything is okay :)
> refactor: add optional chaining

- packages/cli/package.json
- packages/cli/src/commands/init.ts
- packages/cli/src/extensions/nuxt-extension.ts
- packages/cli/src/extensions/shopware-pwa-extension.ts
- packages/default-theme/components/SwBottomNavigation.vue
Dependencies from theme folder. Prepare for release
> refactor(cli):  dependencies from theme

- CONTRIBUTING.md
Just a few slight changes in CONTRIBUTING.md for continious improvement of this awesome document. :)
> Docs: Change some sentences in CONTRIBUTING.md

- packages/composables/__tests__/useCms.spec.ts
- packages/composables/src/hooks/useCms/index.ts
Fixes displaying 500 error page on 404 errors (from page resolver)
> fix(composable): attach entire error object

- CHEATSHEET.md
No issue associated
Fixing the command mentioned for indexing within the `CHEATSHEET.md`
> fix(docs): wrong indexing command

- README.md
In last PR I destroyed the readme. Sorry. :p Fixed the formatting now.
> Fix destroyed README.MD formatting

- packages/shopware-6-client/README.md
- Updated shopware 6 version number in shopware-6-client package README.md
> docs(client): update shopware version in readme

- packages/default-theme/components/SwBottomNavigation.vue
- packages/default-theme/components/SwCart.vue
- packages/default-theme/components/account/MyAddresses/Address.vue
- packages/default-theme/components/cms/elements/SwCategorySidebarFilter.vue
- packages/default-theme/components/forms/SwAddress.vue
- packages/default-theme/components/modals/SwLoginModal.vue
closes: #437 #417 
- allowed access to my account from mobile navigation
- fixed some modal overlays
> fix(theme): allow access to my account from mobile navigation

- packages/default-theme/pages/account/addresses.vue
closes: #441 
- Removed debugging inscription
> fix(theme): remove debugging inscription

- packages/composables/src/index.ts
- packages/composables/src/store.ts
> fix(composables): problem with reference to store in composables package

- .github/workflows/deploy-preview-storefrontcloud.yml
- packages/cli/src/templates/Dockerfile
- [] I followed code and contributing guidelines
PREVIEW_INSTANCE
> Feat/preview deploy test WIP

- packages/nuxt-module/__tests__/module.spec.ts
- packages/nuxt-module/package.json
- packages/nuxt-module/src/interfaces.ts
- packages/shopware-6-client/package.json
- tsconfig.json
- yarn.lock
Remove build warnings about types
> refactor(workflow): remove build warnings

- README.md
- TROUBLESHOOTING.md
closes #361 
It adds _TROUBLESHOOTING.md_ file with gathered common issues and solutions.
The link to the file is added to the _README.md_ as well.
> Feat/create troubleshooting #361

- .github/workflows/deploy-preview-storefrontcloud.yml
fixes the preview deployment process.
> chore: adjust new preview deployment URL

- packages/composables/__tests__/useProductSearch.spec.ts
- packages/composables/src/hooks/useProductSearch.ts
- packages/composables/src/index.ts
- packages/default-theme/components/TopNavigation.vue
closes #466 
- composable added
- search bar added to the top navigation component
> feat: basic search #466

- .github/workflows/deploy-preview-storefrontcloud.yml
Adds a commenting PR mechanism for storefrontcloud.io.
> feat: comment PR with preview_url

- README.md
- packages/nuxt-module/package.json
- packages/nuxt-module/src/index.ts
- yarn.lock
Docs compilation and build types warnings
> chore: docs compilation

- packages/default-theme/components/checkout/ReviewOrder/OrderItem.vue
- packages/default-theme/components/checkout/ReviewOrder/OrderItemsTable.vue
closes #505 
- manage the mobile view for the items
- enable the quantity change on review step
> feat(default-theme): change items quantity on checkout's review.

- packages/default-theme/components/checkout/PersonalDetails.vue
closes #520 
- adds a login modal component
- show login modal on a link click event
> feat(default-theme): allow to log in being on first checkout step.

- packages/commons/interfaces/models/checkout/order/Order.ts
- packages/commons/interfaces/request/CreateGuestOrderParams.ts
related #526 
- adds properties to Order interface (commons package)
- describe the parameters for placing guest order (commons package)
> feat(commons): describe Order interface

- packages/default-theme/components/checkout/PersonalDetails.vue
- packages/default-theme/pages/checkout.vue
closes #507
**PR #518 should be reviewed first!** because changes made in this PR uses the new helper
> feat(default-theme): register a customer on first checkout's step

- packages/default-theme/components/SwRegister.vue
closes #508 
Fix notification computed properties and add styles
> Fix registration notifications

- CHEATSHEET.md
Please merge when master of [SwagShopwarePwa](https://github.com/elkmod/SwagShopwarePwa) is updated.
> Updated shopware plugin name in Cheatsheet

- .github/workflows/deploy-preview-storefrontcloud.yml
- .github/workflows/deploy-storefrontcloud.yml
- CHEATSHEET.md
- README.md
- packages/cli/readme.md
- packages/cli/src/commands/generate.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/extensions/nuxt-extension.ts
- packages/cli/src/extensions/shopware-pwa-extension.ts
- packages/default-theme/package.json
- packages/helpers/src/error/index.ts
- packages/nuxt-module/__tests__/module.spec.ts
- packages/nuxt-module/src/module.ts
- scripts/init.js
- yarn.lock
Fixes problem with loading plugins from other instances than
closes #543
* config now contains only shopware domain
* CLI asks for configuration (first auto-suggestion is from default instance, later from shopware-pwa.config.js file
> fix(cli): load plugins from custom sw instance

- packages/default-theme/components/cms/elements/SwTextSlot.vue
closes #537 
SwTextSlot component is not displayed if it hasn't content
> fix: fix breadcrumbs position

- CHEATSHEET.md
- scripts/generateDocs.js
closes #558, #540 
Fixes docs build process to contain unnecessary files.
> fix(docs): building docs

- .github/workflows/publish-canary.yml
- packages/cli/__tests__/cli-integration.test.ts
- packages/cli/package.json
- packages/cli/src/commands/generate.ts
- packages/cli/src/templates/shopware-pwa.config.js
Deploys canary version for all masters, this PR will have additional docs after ensuring that process is going as it supposed to.
Motivation is to provide fast fixes, which can be tested by the community to provide early-stage feedback.
> feat: deploy canary version from master

- .github/workflows/publish-canary.yml
- packages/cli/package.json
- packages/commons/package.json
- packages/composables/package.json
- packages/default-theme/package.json
- packages/helpers/package.json
- packages/nuxt-module/package.json
- packages/shopware-6-client/package.json
- yarn.lock
*  fixes dependency for require
* fixes canary release with merge
> fix(cli): dependency for require package

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
simplifies PR and issue templates
> chore: simplify PR and issue templates

- packages/cli/package.json
- yarn.lock
closes #584 
The TS version had to be changed in CLI `package.json`
> fix: change CLI TS version

- README.md
- packages/cli/readme.md
Installation of canary version
> docs: canary installation

- CONTRIBUTING.md
- README.md
- packages/cli/readme.md
- packages/default-theme/README.md
> docs: update cli version doc

- api/shopware-6-client.api.md
- packages/commons/interfaces/request/GuestOrderParams.ts
- packages/commons/interfaces/response/ContextTokenResponse.ts
- packages/commons/interfaces/response/SessionContext.ts
- packages/shopware-6-client/__tests__/services/CheckoutService/createOrder.spec.ts
- packages/shopware-6-client/__tests__/services/ContextService/getSessionContext.spec.ts
- packages/shopware-6-client/src/services/cartService.ts
- packages/shopware-6-client/src/services/checkoutService.ts
- packages/shopware-6-client/src/services/contextService.ts
- packages/shopware-6-client/src/services/customerService.ts
> feat: place guest order with proper params and load sessionContext

- CHEATSHEET.md
- README.md
- packages/cli/src/extensions/shopware-pwa-extension.ts
- packages/default-theme/plugins/api-client.js
- packages/shopware-6-client/__tests__/settings.spec.ts
- packages/shopware-6-client/src/settings.ts
updates access token for shopware-2 instance
> feat: update access token for demo instance

- packages/default-theme/cms/elements/CmsElementText.vue
> fix: adjusted banner content

- packages/default-theme/components/SwLogin.vue
- packages/default-theme/components/forms/SwEmail.vue
- packages/default-theme/components/forms/SwPassword.vue
- packages/default-theme/components/forms/SwPersonalInfo.vue
- packages/default-theme/components/modals/SwLoginModal.vue
- packages/default-theme/pages/account.vue
- packages/default-theme/pages/account/orders.vue
- packages/default-theme/pages/account/profile.vue
- packages/default-theme/pages/checkout.vue
- packages/default-theme/pages/login.vue
> refactor: My Account

- packages/cli/src/commands/cms.ts
- packages/cli/src/commands/generate.ts
- packages/cli/src/extensions/cms-extensions.ts
* remove optional chaining from CLI as it's not working in windows and was used only in two lines
* windows resolve of cms paths
> fix(cli): windows cli run

- packages/default-theme/cms/blocks/CmsBlockImageBubbleRow.vue
- packages/default-theme/cms/elements/CmsElementCategoryNavigation.vue
- packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue
- packages/default-theme/cms/elements/CmsElementProductListing.vue
- packages/default-theme/cms/sections/CmsSectionSidebar.vue
- packages/default-theme/components/SwProductGallery.vue
- packages/default-theme/components/SwRegister.vue
- packages/default-theme/components/SwResetPassword.vue
- packages/default-theme/components/TopNavigation.vue
- packages/default-theme/components/modals/SwLoginModal.vue
> refactor: adjusted categories view, small improvements

- packages/default-theme/components/SwLogin.vue
- packages/default-theme/components/SwRegister.vue
- packages/default-theme/components/SwResetPassword.vue
- yarn.lock
closes #290 
Now it's possible to login/register/reset password by using enter button
> feat: add keyup event invoke actions

- packages/default-theme/components/TopNavigation.vue
- packages/default-theme/package.json
- yarn.lock
Update SFUI package version and fix header icons style
> chore: update version and fix styles

- .github/workflows/deploy-preview-storefrontcloud.yml
- .github/workflows/deploy-storefrontcloud.yml
- packages/cli/src/commands/init.ts
- packages/cli/src/extensions/nuxt-extension.ts
- packages/cli/src/extensions/shopware-pwa-extension.ts
- scripts/init.js
closes #700
CLI allows now to choose source distribution of packages and updates dependencies to them
> 700 enable canary and stable mode

- packages/default-theme/cms/elements/CmsElementProductListing.vue
fix listing object structure to 6.1 shopware version
> fix: change propProducts at ProductListing

- .github/workflows/deploy-storefrontcloud.yml
- .github/workflows/publish-canary.yml
- .github/workflows/release-tag.yml
- jest.config.js
- package.json
- packages/cli/package.json
- packages/cli/src/types.ts
- packages/default-theme/package.json
- packages/nuxt-module/package.json
- scripts/bootstrap.js
- scripts/build.js
- scripts/release.js
- scripts/utils.js
- yarn.lock
Added automatization to releases - release script + canary publish support.
> feat: add automatization to releases

- .github/workflows/deploy-storefrontcloud.yml
> fix(workflow): gh action - deploy stable version

- packages/default-theme/components/SwTopNavigation.vue
> MegaMenu fix

- packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue
- packages/default-theme/components/SwCurrency.vue
- packages/default-theme/components/SwProductCard.vue
- packages/default-theme/components/SwTopNavigation.vue
- packages/default-theme/package.json
- yarn.lock
Update SFUI version to 0.7.10 and fix some style issues
> chore: update SFUI version and fix some style issues

- packages/default-theme/components/SwBottomNavigation.vue
Routes to mobile menu are fetch now
> fix: mobile menu routes are fetched now

- CHANGELOG.md
- package.json
- packages/cli/package.json
- packages/commons/package.json
- packages/composables/package.json
- packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue
- packages/default-theme/components/SwTopNavigation.vue
- packages/default-theme/package.json
- packages/helpers/package.json
- packages/nuxt-module/package.json
- packages/shopware-6-client/package.json
- yarn.lock
> feat(default-theme): upgrade SFUI to 0.7.11

- api/composables.api.md
- api/shopware-6-client.api.md
- packages/composables/src/hooks/useUser.ts
- packages/shopware-6-client/__tests__/endpoints.spec.ts
- packages/shopware-6-client/__tests__/services/CustomerService/getCustomerOrderDetails.spec.ts
- packages/shopware-6-client/__tests__/services/CustomerService/getCustomerOrders.spec.ts
- packages/shopware-6-client/src/endpoints.ts
- packages/shopware-6-client/src/services/customerService.ts
- adds the ability to fetch the order details for logged in users
- closes #549
> Feat/store api for customer orders #549

- packages/cli/src/commands/dev.ts
- packages/default-theme/components/SwCart.vue
- packages/default-theme/components/SwTopNavigation.vue
- packages/default-theme/locales/de-DE.json
- packages/default-theme/locales/en-GB.json
- packages/default-theme/logic/index.js
- packages/default-theme/pages/_lang/account.vue
- packages/default-theme/pages/_lang/checkout.vue
- packages/default-theme/pages/_lang/login.vue
closes #116 
Establish i18n structure with fallback for human-readable in case of no translations.
> refactor(default-theme): establish i18n structure

- .github/workflows/deploy-preview-storefrontcloud.yml
- .github/workflows/deploy-storefrontcloud.yml
freezes GH action version - responsible for building docker images
> chore(workflow): docker-building github action upgrade

- packages/default-theme/components/SwProductCard.vue
fix styles for add to cart button on the Product Card
after
before
> fix: add to cart button position on the SwProductCard

- packages/cli/src/commands/init.ts
- packages/cli/src/commands/languages.ts
- packages/cli/src/extensions/nuxt-extension.ts
- packages/default-theme/package.json
- packages/nuxt-module/__tests__/addThemeLayouts.spec.ts
- packages/nuxt-module/__tests__/addThemePages.spec.ts
- packages/nuxt-module/__tests__/extendCms.spec.ts
- packages/nuxt-module/__tests__/extendComponents.spec.ts
- packages/nuxt-module/__tests__/extendLocales.spec.ts
- packages/nuxt-module/__tests__/module.spec.ts
- packages/nuxt-module/__tests__/utils.spec.ts
- packages/nuxt-module/package.json
- packages/nuxt-module/plugins/composition-api.js
- packages/nuxt-module/src/interfaces.ts
- packages/nuxt-module/src/module.ts
- packages/nuxt-module/src/packages.ts
- yarn.lock
Reduces code which was added to default `nuxt.config.js` file and number of dependencies for package.json file.
Diff of changes in nuxt config
and in package.json file (it shows local diff, but you get the point) :)
> feat(cli): reduce nuxt.config changes and package dependencies

- packages/composables/__tests__/useCms.spec.ts
- packages/composables/__tests__/useCurrency.spec.ts
- packages/composables/src/hooks/useCms/index.ts
- packages/composables/src/hooks/useCurrency.ts
- packages/composables/src/logic/useSessionContext.ts
- packages/default-theme/components/SwCurrency.vue
- packages/default-theme/pages/_lang/_.vue
- packages/helpers/__tests__/urlHelpers.spec.ts
- packages/helpers/src/urlHelpers.ts
closes #771
Fixes issue with not reloading the page after currency change and error while reading search query.
Speeds up the process by `~700ms` by not waiting for unnecessary requests.
> fix: currency switch not reloading page #771

- packages/default-theme/components/SwMegaMenu.vue
- packages/default-theme/package.json
- yarn.lock
upgrade SfUI to 0.7.15 and fix no background on SwMegaMenu
> chore: upgrade SfUI to 0.7.15

- packages/composables/src/hooks/useCms/index.ts
- packages/default-theme/cms/blocks/CmsBlockCenterText.vue
- packages/default-theme/cms/blocks/CmsBlockImageFourColumn.vue
- packages/default-theme/cms/blocks/CmsBlockImageHighlightRow.vue
- packages/default-theme/cms/blocks/CmsBlockImageSimpleGrid.vue
- packages/default-theme/cms/blocks/CmsBlockImageTextCover.vue
- packages/default-theme/cms/blocks/CmsBlockImageThreeColumn.vue
- packages/default-theme/cms/blocks/CmsBlockImageThreeCover.vue
- packages/default-theme/cms/blocks/CmsBlockImageTwoColumn.vue
- packages/default-theme/components/SwCart.vue
- packages/default-theme/components/SwFooter.vue
- packages/default-theme/components/SwProductGallery.vue
- packages/default-theme/components/SwRegister.vue
- packages/default-theme/components/SwTierPrices.vue
- packages/default-theme/components/SwTopNavigation.vue
- packages/default-theme/components/checkout/summary/OrderItemsTable.vue
- packages/default-theme/layouts/default.vue
- packages/default-theme/layouts/error.vue
- packages/default-theme/package.json
- packages/default-theme/pages/_lang/_.vue
- packages/default-theme/pages/_lang/success-page.vue
> refactor(default-theme): lazy load cart sidebar

- packages/default-theme/components/SwCartProduct.vue
close #784
the fix can be removed after update SfUI to v0.7.16 or higher
> fix: click:remove emit in SwCartProduct

- packages/default-theme/components/SwProductCardHorizontal.vue
close: #655
add v-model to SwProductCardHorizontal
> fix: quantity in SwProductCardHorizontal

- packages/default-theme/components/SwLogin.vue
- packages/default-theme/components/SwRegister.vue
- packages/default-theme/components/SwResetPassword.vue
- packages/default-theme/components/atoms/SwInput.vue
- packages/default-theme/components/checkout/sidebar/SidebarOrderReview.vue
- packages/default-theme/components/checkout/sidebar/SidebarOrderSummary.vue
- packages/default-theme/components/checkout/steps/guest/BillingAddressGuestForm.vue
- packages/default-theme/components/checkout/steps/guest/PersonalDetailsGuestForm.vue
- packages/default-theme/components/checkout/steps/guest/ShippingAddressGuestForm.vue
- packages/default-theme/components/forms/SwAddress.vue
- packages/default-theme/components/forms/SwPassword.vue
- packages/default-theme/components/forms/SwPersonalInfo.vue
- packages/default-theme/pages/_lang/account/profile.vue
covers; SfInput usage
part of #702
> feat(default-theme): move SfInput into proxy SwInput component

- packages/default-theme/cms/elements/CmsElementProductListing.vue
> fix: pagination on mobile should be centered

- packages/default-theme/cms/blocks/CmsBlockImageSimpleGrid.vue
close #809 
use ::v-deep to include styles
> fix: picture grid is displayed incorrectly

- packages/default-theme/components/SwCartProduct.vue
- packages/default-theme/components/SwProductCard.vue
- packages/default-theme/package.json
fix for 
- a11y 
- unwrappable price
- emit @click:remove in SfCollectedProduct
> chore: update SfUI to 0.7.16

- packages/default-theme/components/SwProductGallery.vue
closes #820
just removed old gallery styles
> fix: product gallery on mobile

- api/helpers.api.md
- docs/api/helpers.getproductregularprice.md
- docs/api/helpers.md
- package.json
- packages/default-theme/components/SwBottomNavigation.vue
- packages/default-theme/components/SwCartProduct.vue
- packages/default-theme/components/SwCurrencySwitcher.vue
- packages/default-theme/components/SwHeader.vue
- packages/default-theme/components/SwHeaderIcons.vue
- packages/default-theme/components/SwLogo.vue
- packages/default-theme/components/SwProductCard.vue
- packages/default-theme/components/SwProductCardHorizontal.vue
- packages/default-theme/components/SwProductDetails.vue
- packages/default-theme/components/SwTopBar.vue
- packages/default-theme/components/SwTopNavigation.vue
- packages/default-theme/components/checkout/steps/guest/PersonalDetailsGuestForm.vue
- packages/default-theme/layouts/default.vue
- packages/helpers/__tests__/product/getProductRegularPrice.spec.ts
- packages/helpers/src/product/getProductRegularPrice.ts
> refactor(default-theme): separate top navigation into smaller components

- packages/default-theme/components/SwOrderDetails.vue
- packages/default-theme/components/SwOrderDetailsItem.vue
- packages/default-theme/components/SwTotals.vue
- packages/default-theme/components/checkout/summary/OrderItem.vue
close #801 
Order details
Thank you page
🚨 @patzick can we move this part of issues to another issues?
> fix: polish order details component

- packages/default-theme/cms/elements/CmsElementProductListing.vue
- packages/default-theme/components/SwProductListing.vue
- packages/default-theme/package.json
- yarn.lock
> fix(default-theme): pagination component

- packages/default-theme/cms/CmsGenericBlock.vue
> feat(default-theme): add custom class to block from cms

- docs/guide/roadmap.md
updates the plans within the roadmap
> docs: roadmap update

- packages/default-theme/pages/_lang/_.vue
closes #843 
views components are now working well with override
> fix(default-theme): overriding views - ProductView, CategoryView

- docs/README.md
- docs/landing/fundamentals/README.md
- docs/landing/fundamentals/security.md
Added a guide in **Fundamentals** > **Security**.
> docs: security fundamental guide

- packages/default-theme/cms/blocks/CmsBlockTextOnImage.vue
> fix(default-theme): align background #854

- packages/default-theme/components/SwOrderDetails.vue
> fix(default-theme): pass the right root context #902

- api/helpers.api.md
- packages/default-theme/cms/CmsGenericBlock.vue
- packages/default-theme/cms/blocks/CmsBlockDefault.vue
- packages/default-theme/cms/blocks/CmsBlockImageBubbleRow.vue
- packages/default-theme/cms/blocks/CmsBlockImageCover.vue
- packages/default-theme/cms/blocks/CmsBlockImageFourColumn.vue
- packages/default-theme/cms/blocks/CmsBlockImageHighlightRow.vue
- packages/default-theme/cms/blocks/CmsBlockImageSimpleGrid.vue
- packages/default-theme/cms/blocks/CmsBlockImageTextCover.vue
- packages/default-theme/cms/blocks/CmsBlockImageTextGallery.vue
- packages/default-theme/cms/blocks/CmsBlockImageThreeColumn.vue
- packages/default-theme/cms/blocks/CmsBlockImageThreeCover.vue
- packages/default-theme/cms/blocks/CmsBlockImageTwoColumn.vue
- packages/default-theme/cms/blocks/CmsBlockTextOnImage.vue
- packages/default-theme/cms/elements/CmsElementImage.vue
- packages/default-theme/components/atoms/SwLink.vue
- packages/helpers/__tests__/cms/getCmsLink.spec.ts
- packages/helpers/__tests__/cms/getCmsLinkTarget.spec.ts
- packages/helpers/__tests__/product/getProductFreeShiping.spec.ts
- packages/helpers/src/cms/getCmsLink.ts
- packages/helpers/src/cms/getCmsLinkTarget.ts
- packages/helpers/src/cms/index.ts
Due to the history rewrite problem, cherry-picked from #901 
closes #432, closes #914
> feat(cms): links inside images block

- packages/default-theme/cms/elements/CmsElementImageSlider.vue
> fix: cms image slider is available

- packages/default-theme/components/SwFooter.vue
- Styled new links on footer section
- Removed unnecessary checkbox component import
Closes #917 
- [ x] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines
> fix(default-theme): added links to footer elements

- packages/cli/src/commands/languages.ts
- packages/cli/src/commands/plugins.ts
- packages/cli/src/extensions/languages-extensions.ts
- packages/cli/src/extensions/plugins-extensions.ts
> feat(plugins): i18n support inside plugins

- api/composables.api.md
- packages/composables/__tests__/useProductListing.spec.ts
- packages/composables/__tests__/useProductSearch.spec.ts
- packages/composables/src/hooks/useProductListing.ts
- packages/composables/src/hooks/useProductSearch.ts
- packages/composables/src/internalHelpers/searchCriteria.ts
- packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue
- packages/default-theme/components/SwProductListingFilters.vue
- packages/default-theme/components/listing/SwProductListingFilter.vue
- packages/default-theme/components/listing/types/entity.vue
- packages/default-theme/components/listing/types/range.vue
- packages/default-theme/pages/_lang/search.vue
- packages/shopware-6-client/__tests__/helpers/convertToStoreApiFilters.spec.ts
- packages/shopware-6-client/src/helpers/convertToStoreApiFilters.ts
closes #840 
- price range filter handling
- refactor of composable
- unification of useProductListing and useProductSearch in terms of toggleFilter and selectedFilters computes
- distinguish the entity and other filters
> Feat(default-theme): handle price filter #840

- docs/landing/concepts/payment.md
There was a mistake in the docs article.
> Payment API docs correction

- packages/composables/src/hooks/useCountries.ts
Fixes problem from our slack channel
> fix(composables): apiInstance used in useCountries causing warning

- packages/default-theme/components/organisms/SwFooterNavigation.vue
> fix(default-theme): catch rejection on footer navigation 

- packages/default-theme/cms/elements/CmsElementProductSlider.vue
- packages/default-theme/cms/sections/CmsSectionDefault.vue
- packages/default-theme/cms/sections/CmsSectionSidebar.vue
> feat(default-theme): cms sections full-width awareness

- packages/default-theme/components/SwCart.vue
- packages/default-theme/components/SwCartProduct.vue
Refactored SwCartProduct component
Fixed some styles in side cart to be more consistent with SFUI designs
Removed unused styles from SwCartProduct component
closes #953
> fix(default-theme): fixed side cart styles

- packages/default-theme/components/SwTopNavigation.vue
> fix(default-theme): require component from default

- packages/default-theme/components/checkout/steps/ShippingStep.vue
Added @click method to go back one step on checkout path
closes #923 #998
> fix(default-theme): fixed back to 1st step checkout button

- packages/shopware-6-client/README.md
updates compatibility version in README file in shopware-6-client package
> docs(client): upgrade compatibility version

- packages/default-theme/components/SwOrderDetails.vue
- packages/default-theme/components/SwOrderDetailsItem.vue
> fix(default-theme): order details styling #959

- packages/default-theme/cms/blocks/CmsBlockProductThreeColumn.vue
> fix(cms): replace fill available with stretch in CmsBlockProductThreeColumn #1009

- docs/guide/CMS.md
- docs/guide/PAYMENT.md
- docs/landing/concepts/cms.md
- docs/landing/concepts/payment.md
- docs/landing/operations/deployment/README.md
- packages/cli/src/extensions/plugins-extensions.ts
- packages/cli/src/extensions/snippets-extension.ts
> fix(cli): adjust CLI invocation to shopware instance

- packages/default-theme/app/router.scrollBehavior.js
- packages/default-theme/assets/scss/main.scss
Changed default scroll behavior
closes #483
> fix(default-theme): changed default scroll behavior

- packages/default-theme/cms/blocks/CmsBlockProductThreeColumn.vue
Removed unnecessary margins
Refactored RWD
Fixed columns height and margins
Big screen:
Tablet screen:
Columns wrapped when the screen is to narrow
Full wrapped on small devices
closes #1028
> fix(default-theme): refactored three columns, product boxes component

- packages/nuxt-module/src/module.ts
connected to #1040 
fixes exact alias to the standard one
> chore: fix alias for components overwriting

- packages/default-theme/cms/elements/CmsElementProductListing.vue
> Fix/product page pagination scroll #1029

- packages/cli/src/extensions/plugins-extensions.ts
> Fix shopware-pwa plugins command (issue #1073)

- packages/composables/src/internalHelpers/defaultApiParams.json
- packages/helpers/__tests__/listing/getListingFilters.spec.ts
- packages/helpers/src/listing/getListingFilters.ts
- packages/helpers/src/listing/index.ts
> feat: getListingFilters & default includes for property option

- packages/shopware-6-client/src/endpoints.ts
I have added comments for new endpoints to be used (I didn't bother doing all the version increments). Some endpoints might slightly change API behaviour, the biggest change is related to guest orders, where an initial register call is required in order to obtain a valid context token.
**Product detail**
Changed `/store-api/v4/product/detail/{productId}` to contain additional information for PDP (like configurator settings, reviews etc.)
> Updated endpoints for Shopware 6.4

- packages/default-theme/cms/blocks/CmsBlockDefault.vue
- packages/default-theme/cms/blocks/CmsBlockForms.vue
- packages/default-theme/cms/blocks/CmsBlockImageBubbleRow.vue
- packages/default-theme/cms/elements/CmsElementCategoryNavigation.vue
- packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue
- packages/default-theme/cms/elements/CmsElementImage.vue
- packages/default-theme/cms/elements/CmsElementProductCard.vue
- packages/default-theme/cms/elements/CmsElementProductListing.vue
- packages/default-theme/cms/elements/CmsElementProductSlider.vue
- packages/default-theme/cms/elements/CmsElementText.vue
- packages/default-theme/cms/elements/CmsElementVideoVimeo.vue
- packages/default-theme/cms/elements/CmsElementVideoYoutube.vue
- packages/default-theme/cms/sections/CmsSectionDefault.vue
- packages/default-theme/cms/sections/CmsSectionSidebar.vue
- packages/default-theme/components/SwOrderDetails.vue
- packages/default-theme/components/SwProductHeading.vue
- packages/default-theme/components/SwProductListing.vue
- packages/default-theme/components/SwProductListingFilters.vue
- packages/default-theme/components/checkout/summary/OrderItemsTable.vue
> refactor(default-theme): change relative imports to use project aliases

- packages/default-theme/components/SwLogin.vue
> fix(default-theme): changed email input to email type

- packages/default-theme/components/SwCheckoutMethod.vue
- packages/default-theme/components/SwOrderDetails.vue
> feat(default-theme): add plugin slots in order details

- README.md
- docs/README.md
- docs/cli/readme.md
- docs/guide/CHEATSHEET.md
- docs/guide/CMS.md
- docs/guide/TROUBLESHOOTING.md
- docs/landing/concepts/cms.md
- docs/landing/concepts/plugins.md
- docs/landing/fundamentals/cli.md
- docs/landing/fundamentals/security.md
- docs/landing/getting-started/README.md
- docs/landing/getting-started/upgrade.md
- docs/landing/operations/deployment/heroku.md
- docs/landing/resources/cheatsheet.md
- docs/landing/resources/troubleshooting.md
- packages/cli/readme.md
- packages/cli/src/extensions/nuxt-extension.ts
- describes how to use shopware-pwa CLI via npx
- should help with getting rid of "obsolete CLI package issues"
> docs: prefer npx  for cli usage

- .github/workflows/pr-check.yml
- docs/landing/project/contribution.md
checks whether the PR title follows the specification.
> ci: add PR title linter in CI process

- docs/landing/project/contribution.md
> docs: info about editing PRs

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
adds an acceptance criteria about updating a feature list in docs.
> chore: github feature template update

- packages/cli/__tests__/buildPluginsMap.spec.ts
- packages/cli/__tests__/buildPluginsTrace.spec.ts
- packages/cli/src/extensions/plugins-extensions.ts
- packages/cli/src/templates/plugins/GenericPlugin.vue
> fix(cli): importing local plugins relative to root instead of src root

- packages/cli/src/extensions/shopware-pwa-extension.ts
> feat(cli): canary instance update

- .github/workflows/publish-canary.yml
> chore(ci): change the API source on canary build

- packages/cli/src/commands/init.ts
- packages/cli/src/extensions/nuxt-extension.ts
closes: #1164
related: #1168 
Helps with the following problems:
and
> fix(cli): error during project initialization

- packages/cli/src/extensions/nuxt-extension.ts
related #1164 
backported functionality to be a stable fix release for 0.4.1
> fix(cli): project initialisation problem

- README.md
- docs/README.md
adds a link to have the possibility of an editable demo in real-time.
> docs: latest stable link to codesandbox editor

- packages/default-theme/src/components/gdpr/SwCookieBar.vue
> fix(default-theme): fixed cookie accept button on safari

- packages/default-theme/src/components/SwProductListingFilters.vue
- packages/shopware-6-client/__tests__/services/PageService/getCmsPage.spec.ts
- packages/shopware-6-client/__tests__/services/PageService/getPage.spec.ts
- packages/shopware-6-client/src/services/pageService.ts
> fix(client): page resolver ssr missing token

- docs/landing/getting-started/upgrade.md
> docs: vuex store migration step for v0.5.x

- docs/README.md
- docs/guide/FEATURELIST.md
> docs: codesandbox link update

- packages/default-theme/src/components/SwMegaMenu.vue
- packages/default-theme/src/components/SwTopNavigation.vue
> fix(default-theme): fixed navigations links alignment

- packages/default-theme/src/components/SwCartProduct.vue
> feat(default-theme): show variant option in cart

- packages/composables/src/logic/useSessionContext.ts
> fix(composables): notify the user in case of refresh session issue

- packages/default-theme/src/components/checkout/steps/guest/PersonalDetailsGuestForm.vue
> fix(default-theme): passing the customer entity during register on checkout

- README.md
> docs: replace greenkeeper badge with new snyk

- packages/default-theme/src/cms/elements/CmsElementContactForm.vue
- packages/default-theme/src/cms/elements/CmsElementNesletterForm.vue
Partially resolves #1231
- I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines **(dead links)**
> fix: errors about displaying errors in NesletterForm

- packages/default-theme/src/components/SwProductListing.vue
> fix(default-theme): watch correct pagination param

- packages/default-theme/src/components/checkout/steps/PaymentStep.vue
- packages/default-theme/src/components/checkout/steps/ShippingStep.vue
- packages/default-theme/src/components/checkout/summary/OrderItem.vue
- packages/default-theme/src/components/checkout/summary/ShippingAddressSummary.vue
- packages/default-theme/src/helpers/index.js
- normalizes the passed slot name for shipping and billing addresses on the checkout
- adds new slots: shipping step, billing step, and summary for shipping method
> feat(default-theme): new slots on checkout

- packages/helpers/src/navigation/getStoreNavigationRoutes.ts
> fix(helpers): get name fallback if there is no translation

- .github/workflows/deploy-preview-storefrontcloud.yml
- docs/landing/resources/api/composables.applicationvuecontext.md
- docs/landing/resources/api/composables.notification_2.md
- docs/landing/resources/api/helpers.storenavigationroute.md
- docs/landing/resources/api/helpers.uicategoryfilteroption.md
- docs/landing/resources/api/shopware-6-client.clientsettings.md
- docs/landing/resources/api/shopware-6-client.contactformdata.md
- docs/landing/resources/api/shopware-6-client.customerresetpasswordparam.md
- docs/landing/resources/api/shopware-6-client.getstorenavigationparams.md
- docs/landing/resources/api/shopware-6-client.newslettersubscribedata.md
- packages/cli/src/extensions/plugins-extensions.ts
- yarn.lock
> chore: deps update

- packages/cli/src/commands/create-theme.ts
> fix: theme template

- packages/default-theme/src/pages/_.vue
> feat(default-theme): cannonical path redirection

- api/shopware-6-client.api.md
- docs/landing/resources/api/shopware-6-client.getcustomerorderdetails.md
- docs/landing/resources/api/shopware-6-client.md
- packages/default-theme/src/components/SwOrderDetails.vue
- packages/default-theme/src/pages/order.vue
- packages/shopware-6-client/__tests__/services/CustomerService/getCustomerOrderDetails.spec.ts
- packages/shopware-6-client/src/services/customerService.ts
> refactor(default-theme): fetching order details and payment redirection

- packages/default-theme/src/components/forms/SwAddressForm.vue
- packages/default-theme/src/pages/account/addresses/add/_id.vue
closes #1245 
TODO: e2e tests covering the address update
> refactor(default-theme): add address form

- packages/cli/src/extensions/nuxt-extension.ts
> feat(nuxt-module): add CHOKIDAR_USEPOLLING flag for development

- packages/default-theme/src/cms/CmsNoComponent.vue
- packages/default-theme/src/cms/elements/CmsElementCategoryNavigation.vue
- packages/default-theme/src/cms/elements/CmsElementContactForm.vue
- packages/default-theme/src/cms/elements/CmsElementNesletterForm.vue
- packages/default-theme/src/components/SwBottomMoreActions.vue
- packages/default-theme/src/components/SwBottomNavigation.vue
- packages/default-theme/src/components/SwProductCarousel.vue
- packages/default-theme/src/components/SwProductDetails.vue
- packages/default-theme/src/components/SwProductHeading.vue
- packages/default-theme/src/components/SwProductListingFilters.vue
- packages/default-theme/src/components/SwProductTabs.vue
- packages/default-theme/src/components/SwSuggestSearch.vue
- packages/default-theme/src/components/SwTierPrices.vue
- packages/default-theme/src/components/checkout/summary/TotalsSummary.vue
- packages/default-theme/src/components/forms/SwAddProductReview.vue
- packages/default-theme/src/components/listing/NoFilterFound.vue
- packages/default-theme/src/layouts/error.vue
- packages/default-theme/src/pages/search.vue
> feat(default-theme): translate static strings

- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/pl-PL.json
few translations added
:heavy_check_mark:
> feat(default-theme): few translations

- .github/workflows/deploy-storefrontcloud.yml
> chore: demo instance update

- package.json
- yarn.lock
> chore: typedoc update

- docs/landing/operations/migrations/0.6.x_to_0.7.x.md
> fix(docs): update 0.6.x_to_0.7.x.md

- packages/default-theme/src/components/SwProductListingFilters.vue
- packages/default-theme/src/components/listing/types/entity.vue
- packages/default-theme/src/components/listing/types/range.vue
- packages/default-theme/src/components/listing/types/rating.vue
- packages/default-theme/src/components/listing/types/shipping-free.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/pl-PL.json
partially closes #1371 
- aggregations don't provide any translation objects to be used, consider using something else.
> feat(default-theme): translate sorting options in product listing

- packages/default-theme/src/components/listing/NoFilterFound.vue
- packages/default-theme/src/components/listing/SwProductListingFilter.vue
properties that the filters are made of, can have name with spaces or special signs. It's better to normalize those name before to avoid spaces in names of vue components or special characters. here's my proposal of using existing helper that replaces non letter characters into "-".
> feat(default-theme): slugify filter type filename

- packages/default-theme/src/logic/useDomains.js
for node v12 and optional chaining
> fix(default-theme): optional chaining compatibility

- .github/workflows/deploy-storefrontcloud.yml
Allow redeploying demo after Shopware config changed.
> chore: allow manual demo deploy

- packages/default-theme/src/components/SwOrderDetails.vue
- packages/default-theme/src/components/checkout/steps/user/ShippingAddressUserForm.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/pl-PL.json
- packages/default-theme/src/pages/account/addresses/index.vue
Add missing 'Add address' translation
> feat(default-theme): add missing 'Add address' translation

- packages/default-theme/src/components/listing/SwProductListingFilter.vue
Removes an unneeded Parameter that appeared after #1385
> fix(default-theme): Remove unneeded parameter

- packages/composables/__tests__/createListingComposable.spec.ts
- packages/composables/__tests__/useProductListing.spec.ts
- packages/composables/__tests__/useProductSearch.spec.ts
- packages/composables/src/factories/createListingComposable.ts
- packages/composables/src/hooks/useProductListing.ts
- packages/composables/src/hooks/useProductSearch.ts
> refactor(composables): remove unnecessary API call from listing

- packages/default-theme/src/components/checkout/steps/user/BillingAddressUserForm.vue
- packages/default-theme/src/components/checkout/steps/user/ShippingAddressUserForm.vue
prevent having not handled errors on second and third step after customer is registered on the checkout.
> fix(default-theme): prevent unexpected error after registering on checkout

- packages/default-theme/src/components/SwTopNavigation.vue
> fix(default-theme): usage of correct lifecycle hook in SwTopNavigation

- compatibility.json
- packages/cli/src/commands/languages.ts
- packages/cli/src/extensions/domains-extension.ts
- packages/cli/src/extensions/snippets-extension.ts
make all admin api calls aligned with new endpoints structure
> feat(cli): v6.4 compatibility for CLI requests

- packages/nuxt-module/__tests__/module.spec.ts
- packages/nuxt-module/plugins/domain.js
- packages/nuxt-module/plugins/i18n.js
- packages/nuxt-module/src/module.ts
closes #1453
compatibility PR from #1458
> fix: default language settings (#1458)

- api/helpers.api.md
- docs/landing/resources/api/helpers.storenavigationroute.md
- docs/landing/resources/api/helpers.storenavigationroute.routepath.md
- packages/helpers/src/navigation/getStoreNavigationRoutes.ts
- packages/shopware-6-client/__tests__/endpoints.spec.ts
- packages/shopware-6-client/__tests__/services/NavigationService/getStoreNavigation.spec.ts
- packages/shopware-6-client/src/endpoints.ts
> feat(client): navigation service

- .github/workflows/deploy-preview-storefrontcloud.yml
- docs/landing/operations/migrations/0.8.x_to_0.9.x.md
- package.json
- packages/cli/src/templates/project-template/package.json
- packages/default-theme/package.json
- packages/default-theme/src/cms/elements/CmsElementContactForm.vue
- packages/default-theme/src/cms/elements/CmsElementNesletterForm.vue
- packages/default-theme/src/components/SwLogin.vue
- packages/default-theme/src/components/SwRegister.vue
- packages/default-theme/src/components/SwResetPassword.vue
- packages/default-theme/src/components/checkout/steps/guest/BillingAddressGuestForm.vue
- packages/default-theme/src/components/checkout/steps/guest/PersonalDetailsGuestForm.vue
- packages/default-theme/src/components/checkout/steps/guest/ShippingAddressGuestForm.vue
- packages/default-theme/src/components/forms/SwAddressForm.vue
- packages/default-theme/src/components/forms/SwPassword.vue
- packages/default-theme/src/components/forms/SwPersonalInfo.vue
- packages/default-theme/src/components/listing/types/range.vue
- packages/default-theme/src/logic/checkout/usePaymentStep.js
- packages/default-theme/src/logic/checkout/usePersonalDetailsStep.js
- packages/default-theme/src/logic/checkout/useShippingStep.js
- packages/nuxt-module/__tests__/__snapshots__/extendNuxtConfig.spec.ts.snap
- packages/nuxt-module/__tests__/module.spec.ts
- packages/nuxt-module/src/extendNuxtConfig.ts
- packages/nuxt-module/src/module.ts
- yarn.lock
closes #1472 
https://shopware-pwa-docs-git-feat-upgrade-vuelidate-v2-shopware-pwa.vercel.app/landing/operations/migrations/0.8.x_to_0.9.x.html#default-theme-upgrading-to-vuelidate-v2-potential-breaking-change
> feat(default-theme)!: upgrade vuelidate with v2

- packages/commons/interfaces/response/SessionContext.ts
- packages/default-theme/src/components/SwOrderDetails.vue
> chore(default-theme): use right method to get payment url

- packages/theme-base/dist/cms/CmsGenericBlock.vue
- packages/theme-base/dist/cms/CmsGenericElement.vue
- packages/theme-base/dist/cms/CmsGenericSection.vue
- packages/theme-base/dist/cms/CmsPage.vue
closes #1484 
Added slots for CMS.
> feat(theme-base): plugin slots for cms pages, sections, blocks and elements

- packages/composables/src/hooks/useUser.ts
- packages/default-theme/src/components/forms/SwRegistrationForm.vue
utilize the getMessagesFromErrorsArray together with SwErrorsList using right data format.
> fix(default-theme): show errors from API in right format

- docs/landing/cookbook/README.md
> docs: info about building a custom theme before usage

- packages/cli/src/extensions/shopware-pwa-extension.ts
closes #1507
Fixes the priorities of settings.
> fix(cli): config file has priority over default settings

- packages/cli/src/commands/domains.ts
fixes issue on accessing to the shopware-pwa config
> fix(cli): access config

- packages/composables/__tests__/useCart.spec.ts
- packages/composables/__tests__/useUser.spec.ts
- packages/composables/src/hooks/useUser.ts
Fix error with refreshing the cart after login/logout
> fix(composables): refresh cart after login/logout

- packages/composables/__tests__/createListingComposable.spec.ts
- packages/composables/src/factories/createListingComposable.ts
fixes problem with category filters
> chore: revert fetching aggregations for filters on category page

- docs/landing/operations/migrations/0.8.x_to_0.9.x.md
extends the migration guide with info about extendNuxtConfig functionality
> docs: nuxt.config.js compatibility

- docs/landing/operations/migrations/0.8.x_to_0.9.x.md
> docs: dependencies issues

- packages/composables/__tests__/useProductConfigurator.spec.ts
- packages/composables/src/logic/useProductConfigurator.ts
> fix(composables): find product variant

- packages/composables/src/internalHelpers/defaultApiParams.json
> fix(composables): product stock includes param

- packages/default-theme/src/pages/checkout.vue
> fix(default-theme): ts error in checkout (vuelidate)

- packages/default-theme/src/components/forms/SwRegistrationForm.vue
closes #1540 
Salutation id is not required, by default we take "not_specified"
> fix(default-theme): salutation in user registration form

- packages/nuxt-module/src/extendNuxtConfig.ts
fixes problem with unavailable devtools in non-production mode
> fix(nuxt-module): revert devtools in non-production mode

- packages/default-theme/src/components/SwBottomNavigation.vue
- packages/default-theme/src/components/SwTopBar.vue
- packages/default-theme/src/components/checkout/CheckoutSummary.vue
- packages/default-theme/src/components/checkout/sidebar/SidebarOrderSummary.vue
- packages/default-theme/src/components/forms/SwAddressManager.vue
- packages/default-theme/src/components/forms/SwRegistrationForm.vue
- packages/default-theme/src/components/modals/SwLoginModal.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/pl-PL.json
closes #1435 
- address management in checkout as a guest user
- logout possibility from guest session + information about guest session
> feat(default-theme): guest session address management and logout possibility

- .github/workflows/deploy-preview-storefrontcloud.yml
- .github/workflows/publish-canary.yml
Do not invoke:
- docs rebuild when nothing in docs folder changed
- preview when only docs changed
- canary publish when only docs changed
-
> chore: workflow improvement

- packages/composables/__tests__/createListingComposable.spec.ts
- packages/composables/src/factories/createListingComposable.ts
> fix(composables): missing aggregation on product listing

- packages/default-theme/src/logic/useDomains.js
> fix(default-theme): correct access to seo urls response elements

- packages/composables/src/hooks/useCms/index.ts
> fix(composables): avoid clearing breadcrumbs

- .github/workflows/copy-forked-branch.yml
> chore: workflow for forked PRs

- docs/landing/resources/api/composables.usedefaults.md
closes #1341 
related #1570 
code by mistake was added to master: https://github.com/vuestorefront/shopware-pwa/commit/9583293730b103c5a1c1dc7b29e872f8a5f422d9
we'll test the preview here and leave PR to have track redord
> chore: update api definition

- packages/default-theme/src/components/SwBottomNavigation.vue
- packages/default-theme/src/components/forms/SwAddProductReview.vue
> fix(default-theme): allow guest customer to log in

- packages/default-theme/src/helpers/pages.js
Fix the problem with CMS not being loaded because marked as static.
> fix(default-theme): static page detection

- packages/cli/src/commands/build-theme.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/cms.ts
- packages/cli/src/commands/create-theme.ts
- packages/cli/src/commands/dev-theme.ts
- packages/cli/src/commands/dev.ts
- packages/cli/src/commands/domains.ts
- packages/cli/src/commands/init.ts
- packages/cli/src/commands/languages.ts
- packages/cli/src/commands/override.ts
- packages/cli/src/commands/plugins.ts
- packages/cli/src/commands/snippets.ts
- packages/cli/src/extensions/plugins-extensions.ts
may be helpful in commands waterfall, especially doing within `init` process.
> feat(cli): prefixes before notifications

- packages/default-theme/src/logic/useDomains.js
- packages/nuxt-module/__tests__/defaultsConfigBuilder.spec.ts
- packages/nuxt-module/src/defaultsConfigBuilder.ts
Fix the problem from community discord: https://discord.com/channels/770285988244750366/786224408460656701/882581558828089364
defaultsConfig builder had a problem with merging arrays
> fix(nuxt-module): defaults config builder array merge

- packages/cli/src/commands/cms.ts
> fix(cli): overwrite CMS elements inside local plugins

- packages/cli/__tests__/buildPluginsMap.spec.ts
- packages/cli/__tests__/buildPluginsTrace.spec.ts
- packages/cli/src/commands/plugins.ts
- packages/cli/src/extensions/plugins-extensions.ts
- packages/cli/src/extensions/shopware-pwa-extension.ts
* added plugins debugging with `--debug` flag (can be used in other commands as well)
* fixed problem with nested plugins pages
> fix(cli): debug mode and problem with nested pages in plugins

- packages/default-theme/__e2e__/specs/passwordReset.spec.js
- packages/default-theme/src/middleware/auth.js
fix the problem from Discord:
credits for @niklaswolf @meeshoogendoorn
> fix(default-theme): reset password form redirection

- packages/default-theme/src/components/SwTermsAndConditions.vue
- packages/default-theme/src/components/checkout/sidebar/SidebarOrderReview.vue
- packages/default-theme/src/components/checkout/summary/SwTermsAgreementCheckbox.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/pl-PL.json
> feat(default-theme): terms and conditions in checkout

- docs/landing/operations/migrations/1.0.0-RC.md
- docs/landing/operations/migrations/README.md
- packages/cli/src/commands/override.ts
- packages/cli/src/templates/project-template/src/components/SwTermsAndConditions.vue
related #772, #1674
Added CLI param, to help override components, added TermsAndConditions component to project template for users as it always requires their input.
> feat(cli): override component with parameters, added TaC to project template

- packages/default-theme/src/layouts/default.vue
- packages/theme-base/dist/app/router.scrollBehavior.js
> fix(default-theme): scroll to anchor links

- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/pl-PL.json
- packages/default-theme/src/pages/checkout.vue
> feat(default-theme): show errors during placing an order

- packages/default-theme/src/components/SwCart.vue
closes #1665 
fixes the error with scrolling inside cart on IOS
> fix(default-theme): fix IOS problem with scrolling inside cart

- packages/default-theme/src/components/forms/SwAddressForm.vue
- packages/default-theme/src/components/forms/SwAddressManager.vue
- solves 500 issues on address change during the checkout
> fix(default-theme): address manager switch problems

- packages/default-theme/src/components/SwBottomNavigation.vue
- packages/theme-base/dist/logic/useLocales.js
While trying to reproduce #1600 I've found that the bottom navi is not opening login window. his PR fixes this issue.
> fix(default-theme): bottom navigation modal invocation

- packages/default-theme/src/components/SwProductDetails.vue
> feat(default-theme): product variant select slot

- packages/composables/src/internalHelpers/defaultApiParams.json
- packages/default-theme/src/components/forms/SwAddressForm.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/pl-PL.json
- packages/default-theme/src/middleware/auth.js
- packages/default-theme/src/pages/account/addresses/add/_id.vue
- packages/default-theme/src/plugins/notifications.js
fixes:
- redirection for current domain on logout/login
- edit address form
adds: 
- notification on customer log out event
> fix(default-theme): log out and edit address improvements

- packages/default-theme/src/helpers/index.js
- packages/shopware-6-client/src/services/searchService.ts
> feat(client): encode search query

- api/composables.api.md
- api/shopware-6-client.api.md
- docs/landing/operations/migrations/1.0.1_to_1.0.2.md
- docs/landing/resources/api/composables.iusecheckout.createorder.md
- docs/landing/resources/api/composables.iusecheckout.md
- docs/landing/resources/api/shopware-6-client.createorder.md
- docs/landing/resources/api/shopware-6-client.md
- packages/commons/interfaces/request/CreateOrder.ts
- packages/composables/__tests__/useCheckout.spec.ts
- packages/composables/src/logic/useCheckout.ts
- packages/shopware-6-client/__tests__/services/CheckoutService/createOrder.spec.ts
- packages/shopware-6-client/src/services/checkoutService.ts
> feat(client): allow to pass additional params in createOrder method

- packages/nuxt-module/plugins/domain.js
> fix(nuxt-module): optional chaining to hasPrefixPath

- packages/default-theme/src/logic/useDomains.js
fixes detecting homepage on domain switch. in order to avoid using technical URL on homepage.
> fix(default-theme): homepage path on domain switch

- .github/workflows/cron-check-demo-uptime.yml
adds a cron job via gh action to check demo sites availability
> chore: check demo sties availability

- packages/composables/package.json
- yarn.lock
closes #1763 for newly generated projects.
> chore: freeze devtools dependency version

- packages/cli/src/templates/project-template/src/plugins/README.md
- packages/nuxt-module/__tests__/module.spec.ts
- packages/nuxt-module/src/module.ts
> feat(nuxt-module): autoload typescript plugins

- api/composables.api.md
- docs/landing/resources/api/composables.swrouting.md
- packages/composables/src/appContext.ts
> fix(composables): add missing type in a routing plugin

- packages/cli/src/commands/create-theme.ts
closes #1784
Fix problem with creating new theme via CLI.
> fix(cli): create theme using CLI

- packages/composables/src/hooks/useUser.ts
- packages/default-theme/src/components/atoms/SwInput.vue
- packages/default-theme/src/components/checkout/summary/OrderItem.vue
- packages/default-theme/src/components/forms/SwPersonalInfo.vue
- packages/default-theme/src/components/gdpr/SwCookieBar.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/nl-NL.json
- packages/default-theme/src/locales/pl-PL.json
- packages/default-theme/src/pages/account/profile.vue
closes: #1808
closes: #1802
closes: #1801
> refactor(default-theme): replace options with composition api in account profile

- docs/landing/concepts/plugins.md
I found this section quite confusing. I have tried to make a few improvements:
- Added basic explanation of pwa plugins ;
- Better explain relation between Shopware plugin and pwa plugin;
> docs: update plugins information

- packages/composables/src/internalHelpers/defaultApiParams.json
- adds id to fetched values for manufacturer entity
> fix(composables): add missing id field to handle filter options for manufacturer

- packages/default-theme/src/components/SwProductHeading.vue
- packages/default-theme/src/components/SwProductTabs.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/nl-NL.json
- packages/default-theme/src/locales/pl-PL.json
- adds pluralization
- adds anchor leading to the reviews on the PDP's bottom
> fix(default-theme): reviews information on PDP

- packages/composables/__tests__/useCart.spec.ts
- packages/composables/src/hooks/useCart/index.ts
> fix(composables): filter empty strings in seo url request

- packages/default-theme/src/cms/elements/CmsElementContactForm.vue
- fixes submit form issue
- closes: #1856
> fix(default-theme): add more data for contact form request

- packages/shopware-6-client/__tests__/apiInterceptors.spec.ts
- packages/shopware-6-client/src/interceptors/errorInterceptor.ts
> fix(client): reveal all errors coming from API within HTTP 4xx group

- README.md
> chore: typo in README.md

- docs/landing/cookbook/README.md
- packages/nuxt-module/__tests__/module.spec.ts
- packages/nuxt-module/src/extendNuxtConfig.ts
- packages/nuxt-module/src/module.ts
- yarn.lock
Config to enable Vuex store, example:
```js
// example nuxt.config.js
import extendNuxtConfig from "@shopware-pwa/nuxt-module/config";
export default extendNuxtConfig({
head: {
title: "Shopware PWA",
meta: [{ hid: "description", name: "description", content: "" }],
},
shopware: {
enableVuex: true,
},
});
```
> feat(nuxt-module): config to enable vuex store

- .github/workflows/deploy-preview-storefrontcloud.yml
> pass full namespace to deploy action

- packages/default-theme/src/components/SwProductCardHorizontal.vue
> fix(default-theme): Fix missing single price in horizontal view 

- packages/default-theme/src/components/SwProductListingFilters.vue
> fix(default-theme): listing hydration

- docs/landing/operations/migrations/1.4.x_to_1.5.1.md
- packages/cli/src/templates/project-template/package.json
- packages/composables/package.json
- packages/default-theme/src/assets/scss/forms.scss
- packages/default-theme/src/components/forms/SwAddressForm.vue
- packages/nuxt-module/package.json
- yarn.lock
> fix: sharedStore is not injected into Vue instance

- packages/default-theme/src/cms/blocks/CmsBlockTextTwoColumn.vue
This PR closes https://shopware.atlassian.net/browse/GS-54
https://user-images.githubusercontent.com/29194019/177505131-96d375f6-84e0-4965-984c-60fcbcee07e5.mp4
> fix(default-theme): Fix text blocks overlap

- packages/default-theme/src/components/SwResetPassword.vue
> fix(default-theme): reset password error list

- api/shopware-6-client.api.md
- docs/landing/resources/api/shopware-6-client.getavailablecurrencies.md
- packages/composables/__tests__/useCurrency.spec.ts
- packages/composables/src/hooks/useCurrency.ts
- packages/shopware-6-client/src/services/contextService.ts
> fix(composables): loading currencies

- packages/default-theme/src/components/forms/SwAddressForm.vue
> fix(default-theme): edit address on ssr

- packages/default-theme/src/pages/account.vue
disclaimer: due to sf-ui limitations on SfContentPage, we can rely only on titles to switch between the subpages.
closes: #1903
> fix(default-theme): prevent redirecting to profile page on SSR

- packages/default-theme/src/components/SwProductListingFilters.vue
- packages/default-theme/src/locales/de-DE.json
- packages/default-theme/src/locales/en-GB.json
- packages/default-theme/src/locales/it-IT.json
- packages/default-theme/src/locales/nl-NL.json
- packages/default-theme/src/locales/pl-PL.json
closes #1926
Related with https://github.com/vuestorefront/shopware-pwa/pull/1908/files
> fix(default-theme): catalog, hydration problem

- packages/default-theme/src/assets/scss/forms.scss
> fix(default-theme): toggle on cancel button

- packages/default-theme/src/cms/elements/CmsElementImage.vue
- packages/default-theme/src/components/atoms/SwImage.vue
- SwImage can not load when there is no thumbnail.
- Update SwImage and CmsElementImage, so it will load with media.url.
> fix(default-theme): Improve SwImage component when no thumbnail

- packages/shopware-6-client/__tests__/services/FormService/newsletterUnubscribe.spec.ts
- packages/shopware-6-client/src/services/formsService.ts
Update Request body of when call news letter unsubscribe API
> fix(client): update newsletter unsubscribe function

- packages/default-theme/src/locales/de-DE.json
fixes translation in German regarding price ranges
> fix(default-theme): price from translation

- packages/default-theme/src/components/SwErrorsList.vue
- packages/default-theme/src/locales/en-GB.json
Move error translations to the application
> feat: error code handling

- packages/default-theme/src/components/views/error.page.vue
fixes translation in German regarding back button in 404 page.
> fix(default-theme): translate text from back button

- packages/default-theme/src/components/atoms/SwImage.vue
- Prevent SwImage lazy loading as default
> feat(default-theme): Prevent img loading lazy as default

- .github/PULL_REQUEST_TEMPLATE.md
Fix the links in the PR template
> chore: fix links in PR template

- packages/cli/src/templates/project-template/package.json
- packages/default-theme/package.json
- packages/default-theme/src/cms/elements/CmsElementImageSlider.vue
- packages/default-theme/src/cms/elements/CmsElementProductSlider.vue
- packages/default-theme/src/components/SwProductCarousel.vue
- destroy Glide before unmount
> fix(default-theme): destroy glide-when-unmount

- packages/default-theme/src/components/SwProductCard.vue
> fix(default-theme): import swpluginslot

- packages/default-theme/src/locales/de-DE.json
German translation for "review"
> chore: Update de-DE.json

- packages/default-theme/src/components/SwProductCarousel.vue
- packages/default-theme/src/components/organisms/SwProductCrossSells.vue
- Change SwProductCarousel & SwProductCrossSells component.
> fix(default-theme): carousel not refresh when cross selling change tab

- packages/default-theme/src/components/listing/types/range.vue
- packages/default-theme/src/components/listing/types/shipping-free.vue
- The value props is not reflect correctly in range and shipping-free components.
> fix(default-theme): sync up data in some filter component
