packages/shopware-6-client/src/interfaces/models/common/Collection.ts, packages/shopware-6-client/src/interfaces/models/common/CustomField.ts, packages/shopware-6-client/src/interfaces/models/common/Entity.ts
**Changes:**
* Add interfaces for `common` group.
* Right now it contains following interfaces: `Entity`, `Collection`, `CustomField`.
**To do:**
* `CustomField` interface to be filled in #61 
**Issue:**
#43
=> #43 - Add interfaces for common models of Shopware 6

package.json, packages/default-theme/components/cms/elements/SwProductGallery.vue, packages/default-theme/components/views/ProductView.vue
Closes #15 
- Separated the product gallery from product view
- Added slots for that component to easily customize the gallery
- Fixed product photo displaying
=> refactor: create component for product gallery

packages/default-theme/components/cms/elements/SwCategoryNavigationSlot.vue
Closes #199 
Fixed links to categories in Category Page.
=> fix(theme): Links to categories do not work in Category Page

.github/workflows/e2e-test.yml, packages/default-theme/components/TopNavigation.vue
In order to get pretty URLs in navigation links and to fit API requirements, some changes in the slug converter have been made. 
It will be unnecessary when navigation endpoints return SEO URLs instead of technical ones.
=> fix: change slug format to fit shopware routing requirements 

packages/default-theme/components/SwLogin.vue, packages/default-theme/components/SwRegister.vue, packages/default-theme/components/modals/SwLoginModal.vue, packages/default-theme/components/views/ProductView.vue
- Fixed problem with displaying modal on product page
- Fixed modal doesn't redirect to reset password
- Changed login input to email input
=> fix(theme): login modal fixes

api/helpers.api.md, api/shopware-6-client.api.md, packages/composables/__tests__/useNavigation.spec.ts, packages/composables/src/hooks/useNavigation.ts, packages/composables/src/hooks/useUser.ts, packages/default-theme/components/SwBottomNavigation.vue, packages/default-theme/components/TopNavigation.vue, packages/default-theme/package.json, packages/helpers/__tests__/navigation/getNavigationRoutes.spec.ts, packages/helpers/src/index.ts, packages/helpers/src/navigation/getNavigationRoutes.ts, packages/helpers/src/navigation/index.ts, packages/shopware-6-client/src/interfaces/models/checkout/customer/CustomerAddress.ts, packages/shopware-6-client/src/interfaces/models/content/navigation/Navigation.ts, packages/shopware-6-client/src/services/cartService.ts, packages/shopware-6-client/src/services/navigationService.ts, yarn.lock
closes #365 
keep in mind: technical URLs will be replaced with the pretty URLs once it's handled on API side.
- new helper to convert navigation from SW API
- add recursion to navi children elements
- not use the slugify anymore: removed from packages
- navigation converter moved from composable "useNavigation"
- some tiny refactor changes
=> feat: use navigation urls taken from API

packages/helpers/__tests__/navigation/getNavigationRoutes.spec.ts, packages/helpers/src/navigation/getNavigationRoutes.ts
It prevents getting wrong urls nesting on route's change. 
- add slash prefix before each given route path
- only helper is affected by this change
=> fix(helpers): prefix route path with slash

packages/default-theme/components/modals/SwLoginModal.vue
closes #435 
- remove unused z-index from #sw-login-modal
- add z-index to .sf-modal__content to fix the bug
=> fix(theme): increase z-index for login modal

.github/workflows/deploy-preview-storefrontcloud.yml, packages/composables/__tests__/useCms.spec.ts, packages/composables/src/hooks/useCms/index.ts
Fixes an issue with displaying wrong error page on 404 from page resolver.
=> fix: proper error object passing

packages/default-theme/components/cms/elements/SwProductListingSlot.vue
closes #445 
Center result text when there are no results.
Before:
After:
=> fix(theme): fix positioning of result text

packages/default-theme/components/cms/elements/SwProductListingSlot.vue
closes #443 
Fix product tile size
Before: 
After:
=> fix(theme): fox wrong product tile size

packages/default-theme/pages/checkout.vue
closes #522 
- adds asyncData in order to check if user is logged in or not - on checkout page
- uses useUser composable
- forces usage of the last step
=> feat(default-theme): force review step for logged in users on checkout

api/helpers.api.md, packages/helpers/__tests__/error/getMessagesFromErrorsArray.spec.ts, packages/helpers/src/error/index.ts, packages/helpers/src/index.ts
Part of work of #507 
covers only helpers package
=> feat(helpers): extract messages from API error in case of 400

packages/default-theme/components/TopNavigation.vue, packages/default-theme/layouts/default.vue
closes: #503 
Change the way of displaying breadcrumbs and plugin top navigation
Before: 
After:
=> fix: change way of displaying breadcrumbs and plugin top navigation

packages/composables/__tests__/useUser.spec.ts, packages/composables/src/hooks/useUser.ts, packages/default-theme/components/SwProductCarousel.vue, packages/default-theme/components/views/ProductView.vue, packages/helpers/src/error/index.ts
prevents displaying error page for async calls which are rejected for some reason
- composable useUser, getCustomer - affected
- default theme async calls on mounted
=> feat: prevent redirecting on api client rejection

packages/shopware-6-client/README.md
sets v6.1.4 shopware version as a compatible.
=> docs: new shopware version compatibility

packages/default-theme/components/SwBottomNavigation.vue
closes: #578 
Add nuxt-link to SfProductOption
=> fix: add nuxt link to buffer SfProductOption

packages/default-theme/components/cms/elements/SwProductListingSlot.vue
closes: #380 
When product collection page is switched there is bllured filter now at product list.
Before:
After:
=> fix: change the way of displaying product collection page switch

packages/default-theme/components/SwLogin.vue, packages/default-theme/components/forms/SwEmail.vue, packages/default-theme/components/forms/SwPassword.vue, packages/default-theme/components/forms/SwPersonalInfo.vue
closes #555 
- fixes my-account update forms issues
- displaying appropriate error messages that come from API in case of 400 (bad request)
=> feat(default-theme): display 400 errors right from the API

packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue
closes #689 
It's possible to click color filter now
=> fix: color select filter is possible to click

packages/default-theme/cms/elements/CmsElementProductListing.vue
closes #654 
cms-element-product-listing class is now set to 100% width;
Before: 
After:
=> fix: set product listing to 100% width

packages/cli/package.json
`copy-templates` npm script fix , because it was an error as below
=> Copy-templates npm script fix

packages/default-theme/cms/cmsMap.json
`CmsBlockDefault` added for `text` and `product-slider` blocks
=> fix: add CmsBlockDefault for slider and text

api/shopware-6-client.api.md, packages/shopware-6-client/__tests__/helpers/convertSearchCriteria.spec.ts, packages/shopware-6-client/__tests__/helpers/convertToStoreApiFilters.spec.ts, packages/shopware-6-client/src/helpers/convertToStoreApiFilters.ts, packages/shopware-6-client/src/helpers/searchConverter.ts
Adds the possibility of filtering within product-listing endpoint.
=> feat(client): filters handler for store-api

packages/default-theme/components/SwProductDetails.vue, packages/default-theme/components/SwProductTabs.vue
allows description to be parsed as html
=> feat(default-theme): parse html tags in product description

.github/workflows/deploy-preview-storefrontcloud.yml
- replace gh action, responsible for deploying PR preview with https://github.com/StorefrontCloud/storefrontcloud-preview-deploy
=> chore: replace github action for deployment on PR preview

api/shopware-6-client.api.md, packages/composables/__tests__/useCheckout.spec.ts, packages/composables/__tests__/useProductListing.spec.ts, packages/composables/src/logic/useCheckout.ts, packages/shopware-6-client/__tests__/endpoints.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/getAvailableCurrencies.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/getAvailableLanguages.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/getAvailablePaymentMethods.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/getAvailableShippingMethods.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/getSessionContext.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/setCurrentBillingAddress.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/setCurrentCurrency.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/setCurrentLanguage.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/setCurrentPaymentMethod.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/setCurrentShippingAddress.spec.ts, packages/shopware-6-client/__tests__/services/ContextService/setCurrentShippingMethod.spec.ts, packages/shopware-6-client/src/endpoints.ts, packages/shopware-6-client/src/services/contextService.ts
closes #551 
- replaces sales-channel-api with store-api if possible
- adjusts parsing the payload for the corresponding endpoints
=> Feat/store api for context related areas #551

docs/guide/PAYMENT.md
=> feat(docs): add usage of shopware-6-client in payment guide

packages/default-theme/layouts/default.vue
we should show outline always when user use tab to the navigation
=> fix(a11y): show outline

packages/default-theme/components/SwLanguageSwitcher.vue
closes #759
the content inside selected el will be center after next storefront-ui release because after that we gen new css variable to fix this case https://github.com/DivanteLtd/storefront-ui/commit/e6c7d1621dd179233556e2d623496a6ab66ef266
Language Selector
Currency selector
=> feat: styling currency and language switchers

packages/cli/src/commands/init.ts, packages/cli/src/commands/plugins.ts, packages/cli/src/extensions/cms-extensions.ts, packages/cli/src/extensions/nuxt-extension.ts, packages/cli/src/extensions/plugins-extensions.ts, packages/cli/src/templates/cms/cmsMap.json, packages/cli/src/templates/cms/readme.md, packages/cli/src/templates/plugins/local-plugins.json, packages/cli/src/templates/plugins/my-local-plugin/config.json, packages/cli/src/templates/plugins/my-local-plugin/myLocalPlugin.vue, packages/cli/src/templates/plugins/readme.md
closes #696, closes #648 
* creates cms directory with cmsMap.json file, cms component folders and readme.md with link to docs
* creates sw-plugin directory with an example plugin (turned off by default) displaying hello world + readme with link to docs
=> feat(cli): generate CMS and plugins folder to easily develop them locally

packages/default-theme/components/SwBottomNavigation.vue, packages/default-theme/components/SwTopNavigation.vue
=> fix: dropdown user icon

packages/default-theme/components/SwProductCard.vue
=> fix: currency sign and price should be in one line

packages/default-theme/cms/blocks/CmsBlockImageSimpleGrid.vue
=> fix: pictures on home page have not equal

packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue, packages/default-theme/components/SwCart.vue, packages/default-theme/components/modals/SwLoginModal.vue
fix z-index in SfSidebra elements (on Filters and Cart)
after
before
=> fix: z-indexes in sidebars and login modal

docs/guide/TROUBLESHOOTING.md
Added troubleshooting advice for outdated cli version leading to incompatible theme version.
It happens when PWA and API version are out of sync and an empty product listing showed up even though products are delivered through the API.
=> docs: additional troubleshooting advise

packages/cli/src/templates/plugins/SwPluginSlot.vue, packages/default-theme/components/SwProductDetails.vue, packages/default-theme/components/views/ProductView.vue, packages/default-theme/layouts/default.vue
Introducing context for plugin slots
- slot with context can have passed context, example
- `<SwPluginSlot name="product-page-description" :slotContext="product">`
- `<SwPluginSlot name="breadcrumbs" :slotContext="getBreadcrumbs" >`
Then in plugin all you need to do is to add props to have expected context:
```vue
<template>
<div class="my-local-plugin">
<h3>Hello from your local plugin!</h3>
<div v-if="slotContext">
<span> {{ slotContext.name }} </span>
<span> {{ slotContext.id }} </span>
</div>
</div>
</template>
<script>
export default {
name: 'MyLocalPlugin',
props: {
slotContext: {
type: Object,
default: null
}
},
data() {
return {}
}
}
</script>
```
result:
=> feat(plugins): context for plugin slots  🚀 

packages/default-theme/cms/elements/CmsElementProductSlider.vue, packages/default-theme/components/SwProductCarousel.vue
=> fix: product carousel on mobile in the horizontal position

CHANGELOG.md, package.json, packages/cli/package.json, packages/cli/src/extensions/nuxt-extension.ts, packages/commons/package.json, packages/composables/package.json, packages/default-theme/package.json, packages/helpers/package.json, packages/nuxt-module/package.json, packages/shopware-6-client/package.json, scripts/release.js
* `create-nuxt-app` cannot handle default answers, we need to use versioned release for now
* added `core-js` to theme dependencies, as it showed errors after Nuxt 2.13 release
=> fix(cli): fix breaking changes after Nuxt 2.13 released

packages/default-theme/helpers/index.js, packages/shopware-6-client/__tests__/services/CustomerService/getCustomerOrders.spec.ts, packages/shopware-6-client/src/services/customerService.ts
closes #792 
- `number of orders` indicator has been fixed in other PR.
=> fix(default-theme): my account order list dates #792

packages/default-theme/components/SwRegister.vue
closes #859 
- gets rid of the port, leave the protocol and domain only as storefrontUrl
=> fix(default-theme): build the right storefront URL during registration

packages/default-theme/components/SwTopNavigation.vue
invoke the navi elements loading again if the navigation array is empty.
watch function from composition api does not trigger the navigation fetching for some reason.
=> fix: load the main navigation elements - watch issue

packages/composables/src/hooks/useProductListing.ts, packages/composables/src/internalHelpers/includesParameter.ts
closes #553 
the product endpoint was handled in previous PR #907 through page resolver.
=> feat(composables): handle the includes parameter within the product listing #553

packages/nuxt-module/__tests__/module.spec.ts, packages/nuxt-module/src/interfaces.ts, packages/nuxt-module/src/module.ts
inspired by #926, changing the config in nuxt-module, and fixing the problem with deploying files, which names start with a dot.
=> chore(nuxt-module): set chunk names for deployment

packages/default-theme/components/SwCurrencySwitcher.vue, packages/default-theme/components/SwHeader.vue, packages/default-theme/components/SwLanguageSwitcher.vue, packages/default-theme/components/SwTopBar.vue, packages/default-theme/layouts/default.vue, packages/default-theme/locales/de-DE.json, packages/default-theme/locales/en-GB.json, packages/default-theme/pages/_lang/account.vue
=> feat: add home path in breadcrumb

packages/cli/__tests__/buildPluginsMap.spec.ts, packages/cli/__tests__/buildPluginsTrace.spec.ts, packages/cli/package.json, packages/cli/src/commands/build.ts, packages/cli/src/commands/dev.ts, packages/cli/src/commands/languages.ts, packages/cli/src/commands/plugins.ts, packages/cli/src/extensions/cms-extensions.ts, packages/cli/src/extensions/languages-extensions.ts, packages/cli/src/extensions/nuxt-extension.ts, packages/cli/src/extensions/plugins-extensions.ts, packages/default-theme/components/SwBottomNavigation.vue
closes #869 
improvements in DX
- package.json will be changed during init to invoke `shopware-pwa dev` or `shopware-pwa build`
- files are watched and proper commands are invoked on those changes
it watches for those events (test scenarios):
- override component
- change anything in CMS components
- change something in local plugins
- change local translations
- change local plugins translations
=> feat(workflow): improve DX by triggering rebuild on changes

packages/default-theme/components/SwTopNavigationShowMore.vue
Added chevron down icon. to the more categories section in navigation.
closes #913
=> fix(default-theme): added icon to more categories

packages/default-theme/components/SwTopNavigation.vue
…ride SfHeader
closes #851 
Replace [this component](https://github.com/DivanteLtd/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfHeader/_internal/SfHeaderNavigationItem.vue) with div to allow override SwHeader
=> refactor(default-theme): allow to override SwHeader without TopNavigation

packages/default-theme/assets/scss/variables.scss, packages/default-theme/cms/settings.scss
Boxed mode blocks have now dynamic max-width css variable set in variables.scss
=> feat(default-theme): boxed-mode max width can now be changed

packages/cli/src/commands/override.ts, packages/nuxt-module/src/components.ts, packages/nuxt-module/src/layouts.ts, packages/nuxt-module/src/module.ts
closes #973 
Fixes components override on Windows 10.
=> fix(nuxt-module): correct aliases to support windows 10 component override

packages/default-theme/assets/scss/variables.scss, packages/default-theme/components/SwBottomNavigation.vue, packages/default-theme/components/SwCart.vue
=> feat(default-theme): bottom navigation always visible on mobile

api/shopware-6-client.api.md, packages/shopware-6-client/__tests__/helpers/convertSearchCriteria.spec.ts, packages/shopware-6-client/__tests__/services/ProductService/getListingProducts.spec.ts, packages/shopware-6-client/src/helpers/searchConverter.ts, packages/shopware-6-client/src/index.ts
changes the parameter for sorting functionality within store-api.
=> fix(client): sorting for store-api

packages/composables/__tests__/useAddToCart.spec.ts, packages/composables/src/logic/useAddToCart.ts
- prevents from seeing 500 while browsing product cards not contained in product listing (like custom cms block). 
- refactor of condition (aligned with 6.3 API change)
=> fix(composables): is in cart condition

packages/shopware-6-client/__tests__/services/CartService/addProductToCart.spec.ts, packages/shopware-6-client/src/services/cartService.ts
If you put the same product into the cart one by one, it creates new items (since there's no `id` passed to the endpoint).
That change was introduced in the the store-api.
**Before:**
**After:**
=> fix(api-client): add product to cart duplicate entries (#1051)

packages/cli/src/extensions/nuxt-extension.ts, packages/nuxt-module/__tests__/module.spec.ts, packages/nuxt-module/src/module.ts
closes #1047 
at the final stage combined static folder is copied to root dir, root dir `static` folder should be placed in gitignore (CLI init does this)
=> chore: fix static folder in dist

packages/default-theme/cms/blocks/CmsBlockTextOnImage.vue
closes #967 
The component now gets the value of image & text and display it next to each other.
Desktop:
Mobile:
=> fix(default-theme): fixed display text next to image in block

packages/default-theme/cms/elements/CmsElementContactForm.vue, packages/default-theme/cms/elements/CmsElementNesletterForm.vue, packages/default-theme/components/SwErrorsList.vue, packages/default-theme/components/atoms/SwAlert.vue, packages/default-theme/components/checkout/steps/guest/PersonalDetailsGuestForm.vue, packages/default-theme/components/forms/SwPassword.vue, packages/default-theme/components/forms/SwPersonalInfo.vue, packages/default-theme/locales/de-DE.json, packages/default-theme/locales/en-GB.json
closes #1053 
- We have created helper to get error messages as an array so here was created "styling component" screen below
- micro refactor on components where errors list exist
- replaced old errors with new ones
=> feat(default-theme): created and styled error list component

packages/composables/__tests__/useProductListing.spec.ts, packages/composables/__tests__/useProductSearch.spec.ts, packages/composables/src/hooks/useProductListing.ts, packages/default-theme/cms/elements/CmsElementCategorySidebarFilter.vue, packages/default-theme/cms/elements/CmsElementProductListing.vue, packages/default-theme/components/listing/types/range.vue, packages/helpers/__tests__/listing/getListingAvailableFilters.spec.ts, packages/helpers/src/listing/filters.ts, packages/helpers/src/listing/getListingAvailableFilters.ts
closes #1043 
closes #1058
closes #1057
closes #834 
TODO:
=> feat: extending available filter api #1043

packages/default-theme/components/SwCart.vue
Fix for scrolling page after closing the cart sidebar.
closes #915 closes #1081
=> fix(default-theme): fix for scrolling page after closing cart

packages/default-theme/cms/blocks/CmsBlockImageText.vue, packages/default-theme/cms/blocks/CmsBlockTextOnImage.vue, packages/default-theme/cms/cmsMap.json
closes #1065 
Created separate file/block for (image text block)
Reverted changes in (text on image block)
Fixed text on image banner at homepage:
Image next to text still looks good:
=> Fix/image text blocks distinction #1065

packages/shopware-6-client/__tests__/services/CartService/removeCartItem.spec.ts, packages/shopware-6-client/src/endpoints.ts, packages/shopware-6-client/src/services/cartService.ts
fixes the current way of deleting a product from cart. 
currently, it wasn't possible to do so, the axios didn't pass the params within the payload, though it was passed correctly to the delete method.
=> fix(api-client): removing cart item correctly

packages/default-theme/components/SwErrorsList.vue
hide the encountered problems list above the specific form when the list is empty
=> fix(default-theme): hide error notifications when the list is empty

packages/default-theme/cms/elements/CmsElementText.vue, packages/default-theme/components/atoms/SwButton.vue
closes #1091 
Now link button Is rendered correctly with link in href attribute. 
Thanks for help @Rigo-m
=> fix(cms): href attribute in the linked text

packages/cli/src/extensions/nuxt-extension.ts
closes #1133 
meta tag added to head section
meta tag has value shopware-pwa
meta tag added to nuxt-extension.ts which generate nuxt.config.js
=> feat(default-theme): added specific meta tag

packages/cli/src/commands/cms.ts, packages/cli/src/commands/languages.ts, packages/cli/src/commands/override.ts, packages/cli/src/extensions/nuxt-extension.ts, packages/cli/src/extensions/shopware-pwa-extension.ts, packages/nuxt-module/__tests__/extendCms.spec.ts, packages/nuxt-module/__tests__/extendLocales.spec.ts, packages/nuxt-module/__tests__/module.spec.ts, packages/nuxt-module/__tests__/useThemeAndProjectFiles.spec.ts, packages/nuxt-module/__tests__/utils.spec.ts, packages/nuxt-module/src/cms.ts, packages/nuxt-module/src/interfaces.ts, packages/nuxt-module/src/module.ts, packages/nuxt-module/src/theme.ts, packages/nuxt-module/src/utils.ts
related: #1158 
The feature allows using another theme as a base, by simply putting its name into `shopware-pwa.config.js` file like this:
```js
module.exports = {
shopwareEndpoint: 'https://pwa-demo-api.shopware.com',
shopwareAccessToken: 'SWSC40-LJTNO6COUEN7CJMXKLA',
// theme: '@shopware-pwa/default-theme',
theme: 'my-theme',
}
```
1. It looks by path, so rootDirectory/path
2. If not found it looks in node modules
Preferably theme should be placed in node_modules so published as NPM package.
Next things to do with the task is to add tools for theme building.
=> feat: ability to use another theme

docs/landing/getting-started/upgrade.md
Remove _not released yet_ notice from the migration guide for 0.5
=> 0.5 has been released meanwhile

packages/helpers/__tests__/product/getProductOptions.spec.ts, packages/helpers/src/product/getProductOptions.ts
Always try to use the translated label/name of an option. If it's not possible, use the entity's name directly.
=> fix(helpers): extract option name from translated object

packages/default-theme/src/components/SwBottomMoreActions.vue
Language and currency switcher only visible in bottom navigation if more than one entry exist
=> fix(default-theme): hide language switcher and currency switcher if only one available (bottom navigation)

packages/helpers/__tests__/category/getCategoryUrl.spec.ts, packages/helpers/src/category/getCategoryUrl.ts
prevent passing the "//" routes to the router-link for category urls. 
nuxt router couldn't parse it as valid URL in `%test-project-dir%/,nuxt/router.js` so it throws an exception during normialization process
=> fix(helpers): prevent double slashes in routes

packages/default-theme/src/components/SwAddress.vue, packages/default-theme/src/components/checkout/steps/guest/BillingAddressGuestForm.vue, packages/default-theme/src/components/checkout/steps/guest/ShippingAddressGuestForm.vue, packages/default-theme/src/components/forms/SwAddressForm.vue, packages/default-theme/src/logic/checkout/usePaymentStep.js, packages/default-theme/src/logic/checkout/useShippingStep.js, packages/default-theme/src/logic/checkout/useUICheckoutPage.js
=> feat(default-theme): remove apartment number from forms

packages/default-theme/src/logic/notifications/index.js, packages/nuxt-module/plugins/i18n.js
closes: #1304 
- injects a plugin in a proper way
- corrects usage of a $t function in interceptors logic
=> fix(nuxt-module): proper i18n plugin injection

packages/default-theme/src/components/SwProductDetails.vue
The "add to cart"  button does not work due to an error: 
> [Vue warn]: Unknown custom element: <SwButton> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
=> fix(default-theme):unknown element SwButton

packages/default-theme/src/cms/elements/CmsElementCategoryNavigation.vue, packages/default-theme/src/locales/de-DE.json, packages/default-theme/src/locales/en-GB.json, packages/default-theme/src/locales/it-IT.json, packages/default-theme/src/locales/pl-PL.json
- use getStoreNavigation instead of deprecated getNavigation method to fetch the subcategories
- use translated names of navi items
- refactor component for composition api style
=> fix(default-theme): missing navigation items and its URLs

packages/default-theme/src/components/checkout/steps/PaymentStep.vue, packages/default-theme/src/components/checkout/steps/ShippingStep.vue, packages/default-theme/src/components/checkout/steps/guest/PersonalDetailsGuestForm.vue, packages/default-theme/src/components/checkout/steps/user/PersonalDetailsUserForm.vue, packages/default-theme/src/components/checkout/summary/TotalsSummary.vue
=> feat(default-theme): adjust buttons in checkout

packages/cli/src/extensions/shopware-pwa-extension.ts
prevents 500 error while requesting shopware instance caused by two slashes in request's url.
=> fix(cli): remove slash from default endpoint

packages/composables/package.json, scripts/linkDependencies.js
reduce composables bundle size, by not bundling helpers and lodash merge method
=> refactor(composables): smaller bundle size

docs/landing/operations/migrations/0.8.x_to_0.9.x.md, packages/cli/src/templates/project-template/package.json, packages/cli/src/templates/project-template/tsconfig.json, packages/nuxt-module/__tests__/__snapshots__/extendNuxtConfig.spec.ts.snap, packages/nuxt-module/__tests__/extendNuxtConfig.spec.ts, packages/nuxt-module/plugins/api-client.js, packages/nuxt-module/src/extendNuxtConfig.ts
You can use TypeScript natively across the project, plugins, theme and logic.
Just add `<script lang="ts">` in your components to start using it there. All your files can be written in `.ts` files.
Quick example:
=> feat: native TypeScript support in components, plugins, theme and project

packages/nuxt-module/__tests__/module.spec.ts, packages/nuxt-module/plugins/domain.js, packages/nuxt-module/plugins/i18n.js, packages/nuxt-module/src/module.ts
closes #1453 
I'll do follow-up PR to master branch
=> fix: default language settings

packages/composables/src/internalHelpers/defaultApiParams.json
solves issue when the property isn't contained in the request's "includes" parameter, it won't be assigned into translated object as well.
=> chore(composables): missing translated names

packages/cli/src/commands/init.ts, packages/cli/src/extensions/shopware-pwa-extension.ts
closes #1517 
- checking if there is not 404 on page resolver's endpoint (default "/" path).
possibly todo: 
- if there is 404 not thrown by Symfony's controller but the page resolver's one.
- distinct 500 & 404, but if there is something wrong with API should be treated as a blocker - as same as an not installed plugin IMO
=> feat(cli): check API access on init

packages/nuxt-module/src/domains.ts
Fix local routes when a domain like `:3000` is registered
=> fix(nuxt-module): sort routes with localhost and port domains

packages/default-theme/src/components/SwProductListing.vue
hides a "next" link on the last page of pagination.
=> fix(default-theme): hide next link in pagination

packages/default-theme/src/components/SwLogin.vue
Fixes problem with `/login` page
=> fix(default-theme): login page validation causing SSR error

packages/default-theme/src/components/checkout/PaymentSection.vue, packages/default-theme/src/pages/checkout.vue
closes #1554 
- enforcing refreshCart method invocation for logged-in users (both, guest and actual).
- enforcing refreshCart on payment method's change
=> fix(default-theme): refresh cart on changes during checkout

packages/default-theme/src/middleware/auth.js
closes #1561 
domains config changes route names, auth middleware was basing its checks on these names. Auth middleware is now redirecting to the login page every time it's used on some page component.
=> fix(default-theme): auth middleware based on route names allowing to show account page

scripts/build.js, scripts/dev.js
closes: #1574 
enforces building packages in production mode to avoid a mode mixing when the nuxt builds the application and gets the pre-built packages.
=> fix: use env from parent process

packages/cli/__tests__/buildPluginsTrace.spec.ts, packages/cli/src/commands/plugins.ts, packages/cli/src/extensions/plugins-extensions.ts
fixes problem with plugin pages and layouts clearing on the runtime
=> fix(cli): plugins pages clearing on the runtime

packages/composables/src/hooks/useCms/index.ts
The issue raised to me by @niklaswolf 
We had a memory leak caused by the watcher invoked on the server-side in the page middleware. I traced that down and after this fix, I see no signs of that.
After we'll confirm that the problem is solved I'll backport it to 0.9 and 0.8 versions as it is a pretty important thing and the fix is not breaking anything.
=> fix(composables): memory leak in the page middleware

docs/landing/operations/deployment/README.md
Changed link from localhost to https://shopware-pwa-docs.vuestorefront.io/ in /docs/landing/operations/deployment/README.md
=> docs: correct link to prepare-shopware.html

packages/nuxt-module/__tests__/defaultsConfigBuilder.spec.ts, packages/nuxt-module/src/defaultsConfigBuilder.ts
closes #1514 
Testing the scenario from the issue I saw that a new key is not created when the path is set.
=> fix(nuxt-module): ability to add new config key for defaults

packages/cli/package.json, packages/cli/src/commands/snippets.ts, packages/cli/src/extensions/plugins-extensions.ts, packages/cli/src/extensions/snippets-extension.ts, yarn.lock
downgrade md5-hex to use cjs in CLI. The problem appeared in `snippets` command
=> fix(cli): downgrade md5-hex to use cjs in CLI

docs/landing/getting-started/README.md, packages/cli/src/commands/plugins.ts, packages/cli/src/extensions/plugins-extensions.ts, packages/cli/src/types.ts, packages/commons/src/defaultConfig.ts
sometimes you may want to disable plugins, which are installed on your shopware instance. Especially when you are locally developing this plugin and want to avoid duplication.
example:
```js
module.exports = {
shopwareEndpoint: "https://pwa-demo-api.shopware.com/trunk/",
shopwareDomainsAllowList: ["http://localhost:3000"],
disabledPlugins: ["my-sw-plugin"],
}
```
this will disable plugin named `my-sw-plugin`
=> feat(cli): ability to disable plugins from shopware instance

packages/nuxt-module/plugins/domain.js
closes #1666 
During SSG both window and request are not reachable. SSG generation should skip domain settings and react on that only on the client side.
=> fix(nuxt-module): ssg mode not working after domains refactor

packages/composables/src/internalHelpers/defaultApiParams.json
added missing include flags for useUser (`defaultBillingAddressId`, `defaultShippingAddressId`, `orderCount`) and useCustomerAddresses (`street`) to make full listing and highlight of current selected address in SwAddressList possible again
=> fix(composables): added missing defaultApiParams in useUser and useCustomerAddresses

api/composables.api.md, docs/landing/resources/api/composables.iusecart.addproduct.md, docs/landing/resources/api/composables.iusecart.md, packages/composables/src/hooks/useCart/index.ts, packages/composables/src/logic/useAddToCart.ts, packages/default-theme/src/plugins/notifications.js
closes: #1217 
- show an error from addToCart response if it's "error level" - everytime
- pushError notification on every broadcasted ERROR event
- do not show success add to cart notification if there is an error with error level in the response
=> fix(composables): show add to cart errors properly

packages/default-theme/src/helpers/index.js, packages/theme-base/dist/helpers/formatPrice.js
Set negativePattern to default pattern to have a consistent format, even on negative prices (like promotions)
=> fix(default-theme): set negativePattern to default

packages/default-theme/src/assets/scss/main.scss, packages/default-theme/src/assets/scss/variables.scss, packages/default-theme/src/cms/settings.scss, packages/theme-base/dist/assets/scss/main.scss, packages/theme-base/dist/assets/scss/variables.scss
closes #1024 
Fixes the perf issue with CSS variables and styles duplication in scoped styles.
In dev mode, it reduced the size of the initial HTML from 494kB -> 291kB
Before:
After:
Reduced around 50kB in production build
=> fix(default-theme): performance issue with css variables duplication

packages/default-theme/src/cms/elements/CmsElementBuyBox.vue, packages/default-theme/src/cms/elements/CmsElementCategoryNavigation.vue, packages/default-theme/src/cms/elements/CmsElementContactForm.vue, packages/default-theme/src/cms/elements/CmsElementImageGallery.vue, packages/default-theme/src/cms/elements/CmsElementProductDescriptionReviews.vue, packages/default-theme/src/components/views/frontend.detail.page.vue, packages/theme-base/dist/pages/_.vue
This is a request from the plugins side. When you want to provide a product context for CmsPage and not use default useCms composable you couldn't reach correct product context.
When you use `CmsPage` component and want to pass additional product context then you can use `provide` mechanism inside the `setup` function. Example from `frontend.detail.page`:
```ts
provide("cms-product", product)
```
from then child components can use this product
```ts
const product = inject("cms-product")
```
=> feat(cms): product context for cms elements

packages/default-theme/src/components/SwCartProduct.vue, packages/default-theme/src/components/SwProductCard.vue, packages/default-theme/src/components/SwProductCardHorizontal.vue, packages/default-theme/src/components/SwProductListing.vue, packages/default-theme/src/components/checkout/sidebar/SidebarOrderReview.vue, packages/default-theme/src/pages/checkout.vue
closes #1698 
closes #1694
Added following slots:
slotContext: product
slotContext: product
slotContext: listing elements
slotContext: null
slotContext: null
slotContext: product
=> feat(default-theme): add requested plugin slots

.vscode/settings.json, packages/composables/__tests__/useSharedState.spec.ts, packages/composables/src/devtools/plugin.ts, packages/composables/src/logic/useSharedState.ts
closes #1727
Fix reactivity issues, when the new reactivity keys were added after the initial page render (for example on page change). The `reactive` object does not allow to dynamically add new keys. This PR fixed the issue.
=> fix(composables): reactivity in local shared state

packages/nuxt-module/plugins/api-client.js
After switching between tabs there was a problem with the synchronisation of the session and card.
For example:
1. go to page
2. open new tam and login
3. go back to page
same with logout
This is the fix for these situations, every time user goes back to the tab we refresh the session and card info to keep that in sync. Additionally, we send interceptor event so you can do additional stuff when it happens using
```
const { on } = useIntercept()
on({
broadcastKey: 'tab-visible',
name: "show-console-message",
handler: () => {
console.log('Welcome back!')
},
})
```
=> fix(default theme):  synchronise tabs after switching between them

packages/default-theme/src/components/SwTopNavigation.vue
VisibleCategories of SwTopNaviation is sometimes null, for example when switching from checkout to home, by clicking the logo. The issue should be fixed after this change.
=> fix(default-theme): SwTopNaviation visibleCategories null variable

packages/default-theme/src/components/modals/SwLoginModal.vue
Translate "Register, "Reset Password" and "Log in"
=> fix(default-theme): missing SwLoginModal translations

packages/nuxt-module/package.json, packages/nuxt-module/plugins/domain.js, yarn.lock
right now only the `X-Forwarded-Host` header is checked when getting the right domain config.
Sadly that wont work in AWS with ALB, there exists the `Forwarded` Header now (Symfony can already deal with that)
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded
If present we take this header into account instead of fallback to the internal host (ip) when the `X-Forwarded-Host` header is missing.
=> feat(nuxt-module): add parsing of "forwarded" header when checking for valid domains

packages/nuxt-module/plugins/api-client.js, packages/shopware-6-client/src/services/checkoutService.ts
-- packages/shopware-6-client/src/services/checkoutService.ts
-- packages/nuxt-module/plugins/api-client.js
-- Added a checker for localStorage item `sw-context-token` when `sw-context-token` cookie was lost in 302 redirect.
-- added a setter for localStorage item `sw-context-token` when redirected to external payment provider.
-- closes #1638 
- [x ] I followed [contributing](https://github.com/DivanteLtd/shopware-pwa/blob/master/CONTRIBUTING.md) guidelines
=> fix(nuxt module): redirect 302 issue on apple devices

api/composables.api.md, docs/landing/resources/api/composables.md, docs/landing/resources/api/composables.usecartitem.md, packages/composables/__tests__/useCart.spec.ts, packages/composables/__tests__/useCartItem.spec.ts, packages/composables/__tests__/useCms.spec.ts, packages/composables/__tests__/useOrderDetails.spec.ts, packages/composables/src/hooks/useCart/index.ts, packages/composables/src/logic/useCartItem.ts, packages/composables/src/logic/useOrderDetails.ts, packages/nuxt-module/__tests__/module.spec.ts, packages/nuxt-module/src/extendNuxtConfig.ts, packages/nuxt-module/src/module.ts
partially closes: #1864
- guess nuxt plugin's mode (client or server) from filename's suffix using pattern: `%plugin_name%.(client|server).(js|ts)`
=> fix(nuxt-module): accept nuxt plugin mode from filename

packages/default-theme/src/cms/elements/CmsElementImage.vue, packages/default-theme/src/components/atoms/SwImage.vue
this PR closes https://github.com/vuestorefront/shopware-pwa/issues/1884
- add new prop `srcset` for SwImage component.
- update srcset data of SwImage inside CmsElementImage component.
=> feat(default-theme): Improve SwImage component with srcset

packages/composables/src/internalHelpers/defaultApiParams.json, packages/default-theme/src/components/SwMegaMenu.vue
this PR closes #714
- default-theme: show category image visible in the top navigation menu.
- composables: add media field for `useNavigation` in defaultApiParams.json.
Before:
After
=> feat(default-theme): Category image in MegaMenu

packages/default-theme/src/components/organisms/SwFooterNavigation.vue, packages/default-theme/src/components/organisms/SwFooterNavigationColumn.vue, packages/default-theme/src/components/organisms/SwFooterService.vue
This PR closes https://github.com/vuestorefront/shopware-pwa/issues/1890
- Create a new component `SwFooterNavigationColumn` to contains the UI of footer column.
- Create a new component `SwFooterService` to fetch service menu from useNavigation.
- Update `SwFooterNavigation` component.
=> feat(default-theme): Add service menu

packages/default-theme/src/components/SwBottomMenu.vue
The default close button for the `SwBottomMenu` has the text "Cancel" hardcoded as value. This change overrides the `close-mobile` slot of the `SfBottomModal` with a button that has the translatable text `Close`.
=> fix(default-theme): override hardcoded close button in bottom menu

packages/default-theme/src/components/account/orders/Order.vue
In the default theme when the order history in a customer's account is viewed in a different language the order status of each order remains empty, since `.name` is used instead of `.translated.name`.
This PR fixes the component.
=> fix(default-theme): Use translated name of order.stateMachineState

api/helpers.api.md, docs/landing/resources/api/helpers.getcmslink.md, docs/landing/resources/api/helpers.getcmslinktarget.md, packages/cli/src/extensions/plugins-extensions.ts, packages/helpers/src/cms/getCmsLink.ts, packages/helpers/src/cms/getCmsLinkTarget.ts, packages/nuxt-module/__tests__/module.spec.ts, packages/nuxt-module/src/module.ts
cli: changes a way how the plugin config json is being fetched, use sync api call instead downloading a static file from the server
nuxt module: Removes a configuration file for the plugins once the build is done.
=> fix(nuxt-module): clean up the dump bundle file after the build

packages/shopware-6-client/__tests__/apiInterceptors.spec.ts, packages/shopware-6-client/src/interceptors/errorInterceptor.ts
Fixes problem of parsing response API messages when API is not reachable
=> fix(api-client): parsing error message when API cannot be reached

packages/default-theme/src/layouts/default.vue
Fixes an issue where the breadcrumb navigation is not usable from product page. There's no need for a redirect method since it uses the nuxt-link in sfLink-Component
Closes https://github.com/vuestorefront/shopware-pwa/issues/1933
- [] the [list of features](docs/guide/FEATURELIST.md) is updated (if it's a feature and it's relevant)
=> fix(default-theme): breadcrumb routing issue

packages/default-theme/src/components/SwProductCard.vue, packages/default-theme/src/components/atoms/SwImage.vue, packages/default-theme/src/components/card/ProductCard.vue
- move logic inside SwProductCard to a new components. This will reduce unnecessary code when dev try to override slot `product-card`
- loading eager will help reduce memory leaks on Safari & firefox
=> feat(default-theme): improve performance

packages/default-theme/src/components/views/frontend.detail.page.vue
The frontend detail page has a bunch of code that doesn't do anything and some scoped styles that don't affect any elements (seems like they are leftovers from some old changes). This PR removes those.
=> chore(default-theme): Remove unused code & styling from detail page

packages/default-theme/src/components/views/error.page.vue
Set the HTTP status code to the correct error code when accessing an error page through SSR. 
This change helps crawlers and scripts to detect the correct status of a page.
closes #1938
=> feat(default-theme): Set HTTP status code when accessing error page through SSR

packages/default-theme/src/components/forms/SwAddressForm.vue
Set the correct property to validate in the form
=> fix(default-theme): SwAddressForm.vue country validation bug

packages/commons/interfaces/models/system/salutation/Salutation.ts
Shopware returns extensions not extenstions, seems to be a typo in the interface
I did not open an issue for this, just saw that my vscode complained about my testdata taken from a real system, which did not match the provided interaface
=> fix: typo in interface

packages/default-theme/src/components/atoms/SwImage.vue
- Add `encodeURI` to the url of srcset.
Before:
After:
=> fix(default-theme): srcset image display wrong incase url have space

.github/workflows/deploy-storefrontcloud.yml, .github/workflows/publish-canary.yml
elgohr/Publish-Docker-Github-Action@master is not supported anymore
=> chore: updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

package.json, packages/commons/interfaces/models/checkout/customer/Customer.ts, packages/commons/interfaces/models/content/landing-page/LandingPage.ts, packages/commons/interfaces/response/SessionContext.ts, packages/composables/__tests__/useCheckout.spec.ts, packages/composables/__tests__/useCustomerOrders.spec.ts, packages/composables/__tests__/useProductReviews.spec.ts, packages/composables/__tests__/useSessionContext.spec.ts, packages/composables/src/hooks/useCustomerOrders.ts, packages/composables/src/internalHelpers/defaultApiParams.json, packages/composables/src/logic/useCheckout.ts, packages/composables/src/logic/useProductReviews.ts, packages/composables/src/logic/useSessionContext.ts, packages/default-theme/src/components/SwProductListingFilters.vue, packages/default-theme/src/components/checkout/CheckoutSummary.vue, packages/shopware-6-client/__tests__/services/CustomerService/getCustomerOrders.spec.ts, packages/shopware-6-client/__tests__/services/FormService/newsletterUnubscribe.spec.ts, packages/shopware-6-client/src/endpoints.ts, yarn.lock
closes: #1992 
- activeBillingAddress
- activeShippingAddress
the fields were replacement by another sources.
for `/navigation` endpoint `seoUrls` association is not necessary anymore. the `sw-include-seo-urls` header does the job.
=> chore: Shopware v6.5 compatibility
